### ISSUE TITLE
Mining Devices Killed

### ISSUE THREAD

**Issue by jarven-zhang** [mimblewimble/grin-miner#100]
I have run the grin and then I run the miner, it connect but disconnect soon.
the miner status is : Waiting for the server 
Last Message Sent : Get new job 
Last Message Received : None

**Comment by jarven-zhang** [comment]
/home/jarven/Pictures/Screenshot from 2019-01-07 14-46-04.png

**Comment by jarven-zhang** [comment]
the node is this 
![screenshot from 2019-01-07 14-42-52](https://user-images.githubusercontent.com/44637785/50753306-6d4d1380-128c-11e9-9f45-564e2bf2b580.png)

**Comment by bryan-lai** [comment]
same issue here

**Comment by scakkia** [comment]
same issue here,
even with
run_tui = false

I'm on Docker on MacOsx 10.12.

The same docker on Linux work fine.

**Comment by quentinlesceller** [comment]
Old issue, closing. Feel free to reopen if this is still relevant.
