### ISSUE TITLE
Miner does not check difficulty

### ISSUE THREAD

**Issue by wsy2220** [mimblewimble/grin-miner#108]
Looks like the solver just report the solution, no matter what difficulty it receives.

See:
https://github.com/tromp/cuckoo/blob/17f752922fdf7a7fd4871a6c257fd0465546ec4c/src/cuckaroo/mean.cu#L699

**Comment by nitronick600** [comment]
Yes this seems to be a problem

**Comment by guybrush** [comment]
solutions get filtered on the cpu https://github.com/mimblewimble/grin-miner/blob/41405bc19370b32a66b31cedb756703bf69528c0/cuckoo-miner/src/miner/miner.rs#L160-L185

**Comment by quentinlesceller** [comment]
This is fixed.
