### ISSUE TITLE
GPU out of memory with "cuckatoo_mean_cuda_gtx_31" on smOS

### ISSUE THREAD

**Issue by royal85** [mimblewimble/grin-miner#113]
I'm running latest smOS and grin-miner 0.5.1.
8GB ram
intel celleron 4400
cards: Nvidia 1080TI's

Error occurs when changing from 29 to 31.

error reason: GPUassert out of memory /home/travis/build/mimblewimble/grin-miner/cuckoo-miner/src/cuckoo_sys/plugins/cuckoo/src/cuckatoo/mean.cu 429

With the following settings that smos runs as a script:
#!/bin/bash                                                                                                                                                                                                 

echo -n > grin-miner.toml                                                                                                                                                                   

echo "[logging]" >> grin-miner.toml
echo "log_to_stdout = true" >> grin-miner.toml
echo "stdout_log_level = \"Info\"" >> grin-miner.toml
echo "log_to_file = false" >> grin-miner.toml
echo "file_log_level = \"Critical\"" >> grin-miner.toml
echo "log_file_path = \"grin-miner.log\"" >> grin-miner.toml
echo "log_file_append = true" >> grin-miner.toml
echo "" >> grin-miner.toml
echo "[mining]" >> grin-miner.toml
echo "run_tui = false" >> grin-miner.toml
echo "" >> grin-miner.toml
echo "stratum_server_addr = \"$1\"" >> grin-miner.toml
echo "stratum_server_login = \"$2\"" >> grin-miner.toml
echo "stratum_server_password = \"$3\"" >> grin-miner.toml
echo "stratum_server_tls_enabled = false" >> grin-miner.toml
echo "" >> grin-miner.toml

NV_GPU_COUNT=`nvidia-smi -L | grep "^GPU " | wc -l`
i=0
while [ $i -lt $NV_GPU_COUNT ]; do
  echo "[[mining.miner_plugin_config]]" >> grin-miner.toml
  echo "plugin_name = \"cuckatoo_mean_cuda_gtx_31\"" >> grin-miner.toml
  echo "[mining.miner_plugin_config.parameters]" >> grin-miner.toml
  echo "device = $i" >> grin-miner.toml
  echo "cpuload = 1" >> grin-miner.toml
  echo "ntrims = 176" >> grin-miner.toml
  echo "genablocks = 4096" >> grin-miner.toml
  echo "genatpb = 128" >> grin-miner.toml
  echo "genbtpb = 128" >> grin-miner.toml
  echo "trimtpb = 512" >> grin-miner.toml
  echo "tailtpb = 1024" >> grin-miner.toml
  echo "recoverblocks = 1024" >> grin-miner.toml
  echo "recovertpb = 1024" >> grin-miner.toml
  i=$((i+1))
done

./grin-miner

**Comment by royal85** [comment]
cuckatoo_mean_cuda_gtx_31 gives the error whyle cuckatoo_lean_cuda_31 runns fine

**Comment by junw3i** [comment]
you can try running `nvidia-smi` on your console and find out if your GPU is hogging any memory.

**Comment by royal85** [comment]
Was first I did. was about 8mb of the 11 gigs. So none of the cards where running out of memory. The miner detects the cards fine. I think maybe the problem is i can't find Cargo.toml anywhere. But cuda runs else cuckatoo_lean_cuda_31 shouldn't have run I think.

When I go to "/root/miner_org/grin-miner-0.5.1/" all I see is the grin-miner, the script I posted above and a plugin directory with all the plugins.

**Comment by tomzo** [comment]
@royal85 I had out of memory like you on 1080ti when using nvidia driver `390.*`.  After upgrading to `410.93` the `cuckatoo_mean_cuda_gtx_31` works, with performance slightly above 0.5 gps.
```
[[mining.miner_plugin_config]]
plugin_name = "cuckatoo_mean_cuda_gtx_31"
[mining.miner_plugin_config.parameters]
device = 0
expand = 2
cpuload = 1
ntrims = 176
genablocks = 4096
genatpb = 128
genbtpb = 128
trimtpb = 512
tailtpb = 1024
recoverblocks = 1024
recovertpb = 1024
```

**Comment by royal85** [comment]
I'm running: NVIDIA-SMI 415.13       Driver Version: 415.13       CUDA Version: 10.0
That's a newer version that you are referring to. Also added the "expand = 2".

**Comment by rheza** [comment]
Hmmm, I'm on hiveos. with 415 driver, also throwing out of memory with cuckatoo_mean_cuda_gtx_31,
but cuckatoo_mean_cuda_Rtx_31 run normal, how ?

**Comment by ignopeverell** [comment]
The Cuckatoo31 variant requires a good 11GB of memory.
