### ISSUE TITLE
Miner not running on nvidia Tesla p100

### ISSUE THREAD

**Issue by rsjandu** [mimblewimble/grin-miner#114]
I am trying to run grin-miner on nvidia Tesla p100 using cuckatoo_lean_cuda_31 config option and getting following error. 

OS: ubuntu 18.04 lts 
Release : https://github.com/mimblewimble/grin-miner/releases/download/0.5.1/grin-miner-0.5.1-476582543-linux-amd64.tgz

**-------ERROR-----**
Jan 10 13:59:43.090 DEBG Loading miner plugin: /home/you/gm/grin-miner-0.5.1/plugins/cuckatoo_lean_cuda_31.cuckooplugin
Jan 10 13:59:43.103 ERRO 
thread 'unnamed' panicked at 'called `Option::unwrap()` on a `None` value': libcore/option.rs:355stack backtrace:
   0:     0x55934fea923d - backtrace::backtrace::trace::h6a895d5d279a8d2f
   1:     0x55934fea8452 - <backtrace::capture::Backtrace as core::default::Default>::default::h03a8d770395d927e
   2:     0x55934fea84c9 - backtrace::capture::Backtrace::new::h2eb1c11c92f206be
   3:     0x55934fe7d030 - grin_miner_util::logger::send_panic_to_log::{{closure}}::h7d93e5b54f679b13
   4:     0x55934fed3896 - std::panicking::rust_panic_with_hook::hde420d6fd4455550
                        at libstd/panicking.rs:480
   5:     0x55934fed33e1 - std::panicking::continue_panic_fmt::h8f394f3c578bcc76
                        at libstd/panicking.rs:390
   6:     0x55934fed32c5 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:     0x55934ff19f8c - core::panicking::panic_fmt::hca5dc4e8b320bc56
                        at libcore/panicking.rs:77
   8:     0x55934ff19ebb - core::panicking::panic::hca17aeb7dac42859
                        at libcore/panicking.rs:52
   9:     0x55934fe61f18 - cuckoo_miner::miner::miner::CuckooMiner::solver_thread::h535da4c06c3d9c30
  10:     0x55934fe644b3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0d585e4948650748
  11:     0x55934fe664b6 - std::panicking::try::do_call::ha175e9372e95fa8f
  12:     0x55934fee3929 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  13:     0x55934fe6dcdd - <F as alloc::boxed::FnBox<A>>::call_box::h09654cb679790681
  14:     0x55934fed0ced - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h9d902c911a417e39
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h44127e03e78ca137
                        at libstd/sys_common/thread.rs:24
  15:     0x55934fec2045 - std::sys::unix::thread::Thread::new::thread_start::h8f17b97f2223146c
                        at libstd/sys/unix/thread.rs:90
  16:     0x7fcaf67696da - start_thread
  17:     0x7fcaf627a88e - __clone
  18:                0x0 - <unknown>

**Comment by dimsav** [comment]
For my case the config had the wrong device number:

Instead of having

```
[[mining.miner_plugin_config]]
plugin_name = “cuckaroo_cuda_29”
[mining.miner_plugin_config.parameters]
device = 1
```

Replacing the `1` with `0` , fixed the problem:

```
[[mining.miner_plugin_config]]
plugin_name = “cuckaroo_cuda_29”
[mining.miner_plugin_config.parameters]
device = 0
```

**Comment by clintar** [comment]
I had that error with driver 395.x and had to upgrade to 415

**Comment by quentinlesceller** [comment]
Closing. Feel free to reopen if this is still relevant.
