### ISSUE TITLE
RpcError 32500

### ISSUE THREAD

**Issue by trummax** [mimblewimble/grin-miner#116]
I have run the grin and then I run the grin-miner, it connects but there is problem.
the miner status is : Starting miner and awaiting first graph time...
Last Message Sent : Get new job
Last Message Received : see screenshot

<img width="567" alt="screenshot 2019-01-11 at 10 25 56" src="https://user-images.githubusercontent.com/22335808/51011492-5871c800-158b-11e9-878c-df30c28da3fe.png">

**Comment by trummax** [comment]
[grin-miner copy.log](https://github.com/mimblewimble/grin-miner/files/2747982/grin-miner.copy.log)

**Comment by quentinlesceller** [comment]
This is a not grin issue but more related to Grinmint. You need to uncomment `stratum_server_login` and `stratum_server_password` from your `grin-miner.toml`. The server will not accept unregistered miners. Closing.
