### ISSUE TITLE
Can not connect to 127.0.0.1:13416

### ISSUE THREAD

**Issue by trummax** [mimblewimble/grin-miner#117]
I have run the grin and then I run the grin-miner, it can not connect to localhost.
the miner status is : Waiting for server
Last Message Sent : None
Last Message Received : None

<img width="564" alt="screenshot 2019-01-11 at 10 43 53" src="https://user-images.githubusercontent.com/22335808/51012191-91f80280-158e-11e9-8a6f-61dcc53076aa.png">

[grin-miner copy.log](https://github.com/mimblewimble/grin-miner/files/2748005/grin-miner.copy.log)

**Comment by junw3i** [comment]
perhaps you need a wallet listener?
`grin wallet listen`

**Comment by trummax** [comment]
"error binding to 127.0.0.1:13415: error creating server listener: Address already in use (os error 48)"
See /Users/johnsmith/.grin/floo/grin-wallet.log for further details.
Wallet command failed: LibWallet Error: Unknown

[grin-wallet copy.log](https://github.com/mimblewimble/grin-miner/files/2748417/grin-wallet.copy.log)

**Comment by trummax** [comment]
'grin wallet listen' works great
