### ISSUE TITLE
Graphics Card is not recognized

### ISSUE THREAD

**Issue by SwaggyLTW** [mimblewimble/grin-miner#118]
I am using a stock Dell G7 Gaming Laptop with a Nvidia GeForce GTX 1060 Max-Q graphics card inside.  The miner does not see my graphics card for whatever reason.  Any advice/help would be very welcomed and appreciated.

**Comment by dafky2000** [comment]
Your GPU needs at least 7GB of video ram. If I am not mistaken the 1060s have a maximum of 6gb? This may be your problem!

**Comment by hashmap** [comment]
Not exactly, with the latest version 5.5 is enough. what is output of `nvidia-smi`?

**Comment by johnalanwoods** [comment]
I have a Radeon Pro 560X 4096 MB graphics, I'm just playing about.

I compiled the miner and I made sure to build the OCL plugins, I get a job but my graph time is 0 and my GPS is inf.

Is it just impossible to mine on this? I thought it would just be slow.

**Comment by hashmap** [comment]
@johnalanwoods you need 8Gb for OpenCL miner

**Comment by quentinlesceller** [comment]
Closing. Feel free to reopen if this is still relevant.
