### ISSUE TITLE
Grin-Miner does not reconnect automatically

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin-miner#130]
When the stratum server restart grin-miner rarely auto reconnect.

**Comment by csga5000** [comment]
I don't see errors - however in log I stop seeing "Recieved message".

It has happened to me numorous times.  I suspect connecting to grinmint and their stratum being overloaded is why disconnects happened so frequently and exacerbated this issue.

**Comment by hashmap** [comment]
I tracked down the issue. Miner reconnects, sends `login` message then `getjobtemplate`. It recieves a vaild `login` response, but next response from Grinmint (in my case) is invalid, it misses both `result` and `error` fields, miner assume at least one of them must be present, so it panics. As result miner's "brain" is dead forever. I'll send a fix, miner must not panic if it receives an invalid message.

```
Jan 16 04:41:28.088 DEBG sending request: {"id":"0","jsonrpc":"2.0","method":"getjobtemplate","params":null}
Jan 16 04:41:28.100 DEBG solver_thread - solver_loop_rx got msg: Pause
Jan 16 04:41:28.100 DEBG solver_thread - solver_loop_rx got msg: Resume
Jan 16 04:41:28.437 DEBG solver_thread - solver_loop_rx got msg: Pause
Jan 16 04:41:30.009 DEBG Received message: {"id":"0","jsonrpc":"2.0","method":"login","result":"ok"}
Jan 16 04:41:30.009 DEBG Received response with id: 0
Jan 16 04:41:30.009 DEBG Received message: {"id":"0","jsonrpc":"2.0","method":"getjobtemplate"}
Jan 16 04:41:30.009 DEBG Received response with id: 0
```

@quentinlesceller I may want to fix sender on your side too, do you think it's an issue in grin stratum impl?

**Comment by yeastplume** [comment]
@hashmap that's excellent, thanks. I was just looking into this as well
