### ISSUE TITLE
/grin-miner: /lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by ./grin-miner)

### ISSUE THREAD

**Issue by TheJenne18** [mimblewimble/grin-miner#136]
Every time I try to run grin-miner, I receive following errors:
Running debian 9.4.
`:~/grin-miner-v1.0.0# ./grin-miner 
./grin-miner: /lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by ./grin-miner)
./grin-miner: /lib/x86_64-linux-gnu/libncursesw.so.5: no version information available (required by ./grin-miner)
./grin-miner: /lib/x86_64-linux-gnu/libncursesw.so.5: no version information available (required by ./grin-miner)
./grin-miner: /lib/x86_64-linux-gnu/libncursesw.so.5: no version information available (required by ./grin-miner)
./grin-miner: /lib/x86_64-linux-gnu/libcrypto.so.1.0.0: version `OPENSSL_1.0.2' not found (required by ./grin-miner)
./grin-miner: /lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.2' not found (required by ./grin-miner)`

FYI:
`~/grin-miner-v1.0.0# apt-cache search ncurses | grep dev
lib32ncurses5-dev - developer's libraries for ncurses (32-bit)
lib32ncursesw5-dev - developer's libraries for ncursesw (32-bit)
lib32tinfo-dev - developer's library for the low-level terminfo library (32-bit)
libcunit1-ncurses-dev - Unit Testing Library for C (ncurses) -- development files
libncurses5-dev - developer's libraries for ncurses
libncursesw5-dev - developer's libraries for ncursesw
libtinfo-dev - developer's library for the low-level terminfo library
libx32ncurses5-dev - developer's libraries for ncurses (x32)
libx32ncursesw5-dev - developer's libraries for ncursesw (x32)
libx32tinfo-dev - developer's library for the low-level terminfo library (x32)
ncurses-doc - developer's guide and documentation for ncurses
btscanner - ncurses-based scanner for Bluetooth devices
libcurses-ocaml-dev - OCaml bindings for the ncurses library
libghc-hscurses-dev - ncurses bindings for Haskell - development files for GHC
libghc-ncurses-dev - Haskell bindings to the GNU ncurses library
libkaya-ncurses-dev - Ncurses binding for kaya
libkaya-ncursesw-dev - Ncurses binding for kaya
libncursesada2-dev - Ada binding to the ncurses text interface library: development
libtexttools3-dev - Ada library for writing console applications: development`

**Comment by QQ40451** [comment]
./grin-miner) ./grin-miner: /lib/x86_64-linux-gnu/libcrypto.so.1.0.0: version OPENSSL_1.0.2' not found (required by ./grin-miner)
./grin-miner: /lib/x86_64-linux-gnu/libssl.so.1.0.0: version OPENSSL_1.0.2' not found (required by ./grin-miner)
upgrade libssl  to 1.0.2 will ok;

**Comment by jjjachyty** [comment]
i was centos 7 

> OpenSSL 1.0.2k-fips  26 Jan 2017
>  libssl3.so        libssl.so.10      libssl.so.1.0.2k 
how to fix it？

**Comment by quentinlesceller** [comment]
Closing. Feel free to reopen if this is still relevant.
