### ISSUE TITLE
Solutions found, but not accepted. However neither rejected nor stale.

### ISSUE THREAD

**Issue by mfronczyk** [mimblewimble/grin-miner#144]
After running the miner for about 4 hours I noticed that it finds solutions, but doesn't report them as accepted, rejected or stale. Please have a look at the screenshot. I don't see "Share accepted" messages in the logs as well. What does it mean?

Is it possible that the miner finds solutions but doesn't send them to the server? Or it means that it sends them, but never hears back if they were accepted or not?

Version 1.0.1, Ubuntu Linux, Mining C31 using RTX

![screenshot from 2019-01-17 08-49-19](https://user-images.githubusercontent.com/5735184/51303190-e1c64600-1a34-11e9-8f37-c0192c39b1c3.png)

**Comment by quentinlesceller** [comment]
Fixed. Closing. Feel free to reopen if this is still relevant.
