### ISSUE TITLE
thread 'unnamed' panicked at 'called `Option::unwrap()` on a `None` 

### ISSUE THREAD

**Issue by SKlayer** [mimblewimble/grin-miner#145]
NVIDIA SMI
`Thu Jan 17 09:04:51 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.59                 Driver Version: 390.59                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P4            Off  | 00000000:08:00.0 Off |                    0 |
| N/A   32C    P8     7W /  75W |     10MiB /  7611MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P4            Off  | 00000000:0D:00.0 Off |                    0 |
| N/A   31C    P8     7W /  75W |     10MiB /  7611MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-PCIE...  Off  | 00000000:0E:00.0 Off |                    0 |
| N/A   34C    P0    25W / 250W |     11MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
`

Miner Log
Release version 1.02, Ubuntu

`Jan 17 09:03:33.631 INFO This is Grin-Miner version 1.0.2 (git v1.0.2), built for x86_64-unknown-linux-gnu by rustc 1.31.1 (b6c32da9b 2018-12-18).
Jan 17 09:03:33.631 DEBG Built with profile "release", features "CURSIVE, DEFAULT, OCL_CUCKAROO, OCL_CUCKATOO, OPENCL, TUI" on Thu, 17 Jan 2019 09:43:20 GMT.
Jan 17 09:03:33.631 DEBG Starting solvers
Jan 17 09:03:33.631 DEBG Using mining plugin dir provided by config: "/home/li.zhang/mining_test/grin-miner-v1.0.2/plugins"
Jan 17 09:03:33.631 DEBG Loading miner plugin: /home/li.zhang/mining_test/grin-miner-v1.0.2/plugins/cuckaroo_cuda_29.cuckooplugin
Jan 17 09:03:33.631 DEBG Loading miner plugin: /home/li.zhang/mining_test/grin-miner-v1.0.2/plugins/cuckaroo_cuda_29.cuckooplugin
Thread 'unnamed' panicked with message:
"called `Option::unwrap()` on a `None` value"
See grin.log for further details.
Jan 17 09:03:33.669 ERRO
thread 'unnamed' panicked at 'called `Option::unwrap()` on a `None` value': libcore/option.rs:355stack backtrace:
   0:     0x5636adeec63d - backtrace::backtrace::trace::h6a895d5d279a8d2f
   1:     0x5636adeeb852 - <backtrace::capture::Backtrace as core::default::Default>::default::h03a8d770395d927e
   2:     0x5636adeeb8c9 - backtrace::capture::Backtrace::new::h2eb1c11c92f206be
   3:     0x5636adec0420 - grin_miner_util::logger::send_panic_to_log::{{closure}}::h4bb1012a1843d723
   4:     0x5636adf18f56 - std::panicking::rust_panic_with_hook::hde420d6fd4455550
                        at libstd/panicking.rs:480
   5:     0x5636adf18aa1 - std::panicking::continue_panic_fmt::h8f394f3c578bcc76
                        at libstd/panicking.rs:390
   6:     0x5636adf18985 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:     0x5636adf5f64c - core::panicking::panic_fmt::hca5dc4e8b320bc56
                        at libcore/panicking.rs:77
   8:     0x5636adf5f57b - core::panicking::panic::hca17aeb7dac42859
                        at libcore/panicking.rs:52
   9:     0x5636adea482a - cuckoo_miner::miner::miner::CuckooMiner::solver_thread::h71096cba5c9f9455
  10:     0x5636adeaf5a3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3cd28aa69629792f
  11:     0x5636adeac468 - std::panicking::try::do_call::h449225a1a057b28a
  12:     0x5636adf28fe9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  13:     0x5636adeb0bed - <F as alloc::boxed::FnBox<A>>::call_box::h1f186ce093ce965b
  14:     0x5636adf163ad - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h9d902c911a417e39
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h44127e03e78ca137
                        at libstd/sys_common/thread.rs:24
  15:     0x5636adf076c5 - std::sys::unix::thread::Thread::new::thread_start::h8f17b97f2223146c
                        at libstd/sys/unix/thread.rs:90
  16:     0x7f43b875f6b9 - start_thread
  17:     0x7f43b827f41c - clone
  18:                0x0 - <unknown>

Jan 17 09:03:34.806 WARN Connection Status: Connected to Grin server at cn-grin.ss.btc.com:1800.
Jan 17 09:03:34.816 DEBG sending request: {"id":"0","jsonrpc":"2.0","method":"login","params":{"agent":"grin-miner","login":"pvr.001","pass":""}}
Jan 17 09:03:34.816 DEBG sending request: {"id":"0","jsonrpc":"2.0","method":"getjobtemplate","params":null}
Jan 17 09:03:35.008 DEBG Received message: {"id":"0","jsonrpc":"2.0","method":"login","result":"ok","error":null}

Jan 17 09:03:35.008 DEBG Received response with id: 0
Jan 17 09:03:35.009 DEBG Received message: {"id":"Stratum","jsonrpc":"2.0","method":"job","params":{"difficulty":1,"height":2542,"job_id":4281575556,"pre_pow":"000100000000000009ee000000005c408b2d000013b72ddcc0f0cc069ff444323448271724ab5613b20c62e036f4b7debef3d4c6710aad6ac030dc712969cfe73e6477cc1edc7aa97e4d9cf9e2ae22a54d727154d1798f29dc05da0042d950adb57a740e0dae5c1fff5879229e9af61007ce5265867839bf7c96ce3f128a1dbe3c94605120deb274edaf14934d5f2b822d5fb68ba093c45b9088c33c32d3491ac6e390d715aa2e31c106c555e3fe99a15ccbf38a089570f7f4dcf4a0efce4f16c3e776481d67f6945150683e4b2d38cd4de700000000000025e90000000000001b1b0000015a7db1e919000003c0"}}

Jan 17 09:03:35.009 DEBG Received request type: job
Jan 17 09:03:35.009 INFO Got a new job: JobTemplate { height: 2542, job_id: 4281575556, difficulty: 1, pre_pow: "000100000000000009ee000000005c408b2d000013b72ddcc0f0cc069ff444323448271724ab5613b20c62e036f4b7debef3d4c6710aad6ac030dc712969cfe73e6477cc1edc7aa97e4d9cf9e2ae22a54d727154d1798f29dc05da0042d950adb57a740e0dae5c1fff5879229e9af61007ce5265867839bf7c96ce3f128a1dbe3c94605120deb274edaf14934d5f2b822d5fb68ba093c45b9088c33c32d3491ac6e390d715aa2e31c106c555e3fe99a15ccbf38a089570f7f4dcf4a0efce4f16c3e776481d67f6945150683e4b2d38cd4de700000000000025e90000000000001b1b0000015a7db1e919000003c0" }
Jan 17 09:03:35.009 DEBG Received message: {"id":"0","jsonrpc":"2.0","method":"getjobtemplate","result":{"difficulty":1,"height":2542,"job_id":4281575556,"pre_pow":"000100000000000009ee000000005c408b2d000013b72ddcc0f0cc069ff444323448271724ab5613b20c62e036f4b7debef3d4c6710aad6ac030dc712969cfe73e6477cc1edc7aa97e4d9cf9e2ae22a54d727154d1798f29dc05da0042d950adb57a740e0dae5c1fff5879229e9af61007ce5265867839bf7c96ce3f128a1dbe3c94605120deb274edaf14934d5f2b822d5fb68ba093c45b9088c33c32d3491ac6e390d715aa2e31c106c555e3fe99a15ccbf38a089570f7f4dcf4a0efce4f16c3e776481d67f6945150683e4b2d38cd4de700000000000025e90000000000001b1b0000015a7db1e919000003c0"}}

Jan 17 09:03:35.009 DEBG Received response with id: 0
Jan 17 09:03:35.009 INFO Got a job at height 2542 and difficulty 1
Jan 17 09:03:35.035 DEBG Miner received message: ReceivedJob(2542, 4281575556, 1, "000100000000000009ee000000005c408b2d000013b72ddcc0f0cc069ff444323448271724ab5613b20c62e036f4b7debef3d4c6710aad6ac030dc712969cfe73e6477cc1edc7aa97e4d9cf9e2ae22a54d727154d1798f29dc05da0042d950adb57a740e0dae5c1fff5879229e9af61007ce5265867839bf7c96ce3f128a1dbe3c94605120deb274edaf14934d5f2b822d5fb68ba093c45b9088c33c32d3491ac6e390d715aa2e31c106c555e3fe99a15ccbf38a089570f7f4dcf4a0efce4f16c3e776481d67f6945150683e4b2d38cd4de700000000000025e90000000000001b1b0000015a7db1e919000003c0")
Jan 17 09:03:35.035 DEBG Pause message sent
Jan 17 09:03:35.035 DEBG Resume message sent
Jan 17 09:03:35.035 DEBG Miner received message: ReceivedJob(2542, 4281575556, 1, "000100000000000009ee000000005c408b2d000013b72ddcc0f0cc069ff444323448271724ab5613b20c62e036f4b7debef3d4c6710aad6ac030dc712969cfe73e6477cc1edc7aa97e4d9cf9e2ae22a54d727154d1798f29dc05da0042d950adb57a740e0dae5c1fff5879229e9af61007ce5265867839bf7c96ce3f128a1dbe3c94605120deb274edaf14934d5f2b822d5fb68ba093c45b9088c33c32d3491ac6e390d715aa2e31c106c555e3fe99a15ccbf38a089570f7f4dcf4a0efce4f16c3e776481d67f6945150683e4b2d38cd4de700000000000025e90000000000001b1b0000015a7db1e919000003c0")
Jan 17 09:03:36.036 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 17 09:03:36.036 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
^C
`

**Comment by SKlayer** [comment]
This is my config
`
[logging]
log_to_stdout = true
stdout_log_level = "Debug"
log_to_file = false
log_file_path = "grin-miner.log"
file_log_level = "Debug"
log_file_append = true

[mining]

run_tui = false

stratum_server_addr = "cn-grin.ss.btc.com:1800"
stratum_server_login = "pvr.001"
stratum_server_tls_enabled = false
miner_plugin_dir = "plugins"

[[mining.miner_plugin_config]]

plugin_name = "cuckaroo_cuda_29"

[mining.miner_plugin_config.parameters]
device = 0
expand = 2
cpuload = 1
ntrims = 176
genablocks = 4096
genatpb = 128
genbtpb = 128
trimtpb = 512
tailtpb = 1024
recoverblocks = 1024
recovertpb = 1024
`

**Comment by apruden2008** [comment]
Is your .toml file in the same directory as your exe?  That was my issue

**Comment by SKlayer** [comment]
> Is your .toml file in the same directory as your exe? That was my issue

yes, it is default path. i does not make changes

**Comment by aaronwinter** [comment]
@SKlayer Make sure that the `grin-miner.toml` configuration file is in your *current* working directory.

e.g

`machine@host:$ ./target/release/grin-miner`

**Comment by SKlayer** [comment]
cpu mining is work, only use GPU crash. trying to switch solverplugin but still crash

**Comment by quentinlesceller** [comment]
Closing. Feel free to reopen if this is still relevant.
