### ISSUE TITLE
how to use grin-miner on centos6?

### ISSUE THREAD

**Issue by Tennysony** [mimblewimble/grin-miner#147]
my system is centos6.x. but grin-miner can't work. so,how to use grin-miner binary on centos6? how to build grin-miner on centos6?

**Comment by QbiX90** [comment]
No way even on CentOS7....

**Comment by pmoneymd** [comment]
I've managed to get it running on CentOS7. What issues are you having?

**Comment by jjjachyty** [comment]
> I've managed to get it running on CentOS7. What issues are you having?

i was centos7 

> ./grin-miner: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
> ./grin-miner: /lib64/libtinfo.so.5: no version information available (required by ./grin-miner)
> ./grin-miner: /lib64/libncursesw.so.5: no version information available (required by ./grin-miner)
> ./grin-miner: /lib64/libncursesw.so.5: no version information available (required by ./grin-miner)
> ./grin-miner: /lib64/libncursesw.so.5: no version information available (required by ./grin-miner)
> ./grin-miner: /lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./grin-miner)
> ./grin-miner: /lib64/libssl.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./grin-miner)

/usr/lib64 with libssl

> libssl3.so

        libssl.so.10      libssl.so.1.0.0   libssl.so.1.0.2k

**Comment by glemercier** [comment]
Centos has some architectural differences with debian/ubuntu for which the prebuilt binaries seem to have been built for. You can make it work by building it from source, it should be straight-forward if you follow the steps here https://github.com/mimblewimble/grin-miner/blob/master/README.md

Note that you'll need cmake > 3.2 that does not seem to be avilable through centos package repository. You may want to follow this guide to build a newer version from source: http://jotmynotes.blogspot.com/2016/10/updating-cmake-from-2811-to-362-or.html

**Comment by quentinlesceller** [comment]
Closing. Feel free to reopen if this is still relevant.
