### ISSUE TITLE
failed to build： recipe for target 'CMakeFiles/cuckatoo_mean_cpu_compat_31.dir/cuckoo/src/cuckatoo/mean.cpp.o' failed CMakeFiles/Makefile2:326: recipe for target 'CMakeFiles/cuckatoo_mean_cpu_compat_31.dir/all' failed

### ISSUE THREAD

**Issue by jackzhp** [mimblewimble/grin-miner#150]
Can someone please help me with this? Thanks.
What is wrong for my case? The building failed with the following relevant info:

[ 63%] Built target cuckatoo_lean_cpu_avx2_31
Scanning dependencies of target cuckatoo_mean_cpu_compat_31
[ 66%] Building CXX object CMakeFiles/cuckatoo_mean_cpu_compat_31.dir/cuckoo/src/cuckatoo/mean.cpp.o
CMakeFiles/cuckatoo_mean_cpu_compat_31.dir/build.make:62: recipe for target 'CMakeFiles/cuckatoo_mean_cpu_compat_31.dir/cuckoo/src/cuckatoo/mean.cpp.o' failed
CMakeFiles/Makefile2:326: recipe for target 'CMakeFiles/cuckatoo_mean_cpu_compat_31.dir/all' failed
Makefile:83: recipe for target 'all' failed

--- stderr
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/immintrin.h:37:0,
                 from /data43/dev/grin/grin-miner/cuckoo-miner/src/cuckoo_sys/plugins/cuckoo/src/cuckatoo/../crypto/siphashxN.h:3,
                 from /data4/dev/grin/grin-miner/cuckoo-miner/src/cuckoo_sys/plugins/cuckoo/src/cuckatoo/mean.hpp:11,
                 from /data4/dev/grin/grin-miner/cuckoo-miner/src/cuckoo_sys/plugins/cuckoo/src/cuckatoo/mean.cpp:4:
/usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h: In member function ‘void edgetrimmer::genUnodes(u32, u32)’:
/usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h:454:1: error: inlining failed in call to always_inline ‘long long int _mm_extract_epi64(__m128i, int)’: target specific option mismatch
 _mm_extract_epi64 (__m128i __X, const int __N)
 ^

**Comment by glemercier** [comment]
Can you provide more info on your setup? Machine, OS, etc...

**Comment by quentinlesceller** [comment]
This is fixed. Closing. Feel free to reopen if this is still relevant.
