### ISSUE TITLE
Build failure: error[E0433]: failed to resolve. Use of undeclared type or module `util`          

### ISSUE THREAD

**Issue by gms2009** [mimblewimble/grin-miner#156]
Compiling cuckoo_miner v1.0.2 (/home/weilo/Downloads/grin/grin-miner/cuckoo-miner)
error[E0433]: failed to resolve. Use of undeclared type or module `util`        
   --> cuckoo-miner/src/miner/consensus.rs:208:3                                
    |                                                                           
208 |         util::to_hex(self.0.to_vec())                                     
    |         ^^^^ Use of undeclared type or module `util`                      
                                                                                
error: aborting due to previous error                                           
                                                                                
For more information about this error, try `rustc --explain E0433`.             
error: Could not compile `cuckoo_miner`.                                        

tried on ubuntu 16.04 and 18.04

**Comment by dregimbal** [comment]
I'm also getting this on Ubuntu 18.10

**Comment by dregimbal** [comment]
Fixed by adding 
use util;
to consensus.rs

**Comment by yeastplume** [comment]
please use latest rust for building
