### ISSUE TITLE
fatal runtime error: failed to initiate panic: error 5

### ISSUE THREAD

**Issue by JonathonJulian** [mimblewimble/grin-miner#159]
Hi,

Just testing out grin-miner using for CPU mining on EC2. I setup per this procedure
https://blog.blockcypher.com/mining-grin-on-grinmint-a-step-by-step-tutorial-98235c038876

my node and miner are on separate instances, when i start the miner i get the following error,  hoping someone can point me in a direction to troubleshoot. 

fatal runtime error: failed to initiate panic: error 5, Aborted (core dumped)

I am using micro instances with only 1GB RAM, not sure if thats related, afaik my config is good.

**Comment by bhc8521** [comment]
i have same problem, how to fix it?
