### ISSUE TITLE
I can not find floonet coins, very high difficulty

### ISSUE THREAD

**Issue by carl0sfelipe** [mimblewimble/grin-miner#162]
The testnet is very scarce, I can not find or mine, I think we need to change the difficulty setting of the testnet as it was done in Bitcoin's Testnet3.

I think that abundant testnet coins are important for development and learning, even more in a new innovative protocol such as grin.

**Comment by ignopeverell** [comment]
Floonet difficulty is coming down little by little. If you want to help, mine on it for as long as possible. It'll be usable again in a day or two.

**Comment by ignopeverell** [comment]
We could but I don't think we should unless this becomes a recurring situation. We're not going to have a ton of hashpower getting ready for mainnet and suddenly disappearing from floonet very often...

**Comment by rheza** [comment]
Sorry though, but what for you guys mining Floonet?, just testing ?

**Comment by hitchcott** [comment]
Is there an alternative way to get floonet grins without waiting for days?

**Comment by jasonzhouu** [comment]
```
Thanks to Photon, you can ask for some free test Grin coins simply by running this command on your node.
	curl gringod.info
	grin wallet info
```
https://medium.com/@pavol.travnik/grin-mimblewimble-24d5b2116649
