### ISSUE TITLE
Miner doesn't work after network reset

### ISSUE THREAD

**Issue by winbucks** [mimblewimble/grin-miner#165]
Grin Miner v.1.0.2 stop mining or stop send/receive after network reset. 
Mining appears to be working (graph time changes, GPS changes).
Last Message Sent/Received appears to be static.
No solutions found after 10 minutes.
Running on Ubuntu 18.04.1 LTS

**Comment by cost82el** [comment]
same issue... i restarted router... grin miner cant auto connect to pool?

**Comment by quentinlesceller** [comment]
Closing. Feel free to reopen if this is still relevant.
