### ISSUE TITLE
>10 GPU 1080ti+1070 issue

### ISSUE THREAD

**Issue by PePPeRmix** [mimblewimble/grin-miner#166]
Hello, rig got 12 GPUs, 4x1070 (0,1,2,5) and 8x1080ti(3,4,6,7,8,9,10,11).
But miner see different numbers, and he think all GPUs is 1080ti 
![01](https://user-images.githubusercontent.com/584055/51787493-c0c3ca80-2183-11e9-9fdb-6bdba7dcc307.JPG)
![02](https://user-images.githubusercontent.com/584055/51787494-c0c3ca80-2183-11e9-80b8-afcb95f98390.JPG)
for this error i can't run different algo like 31 and 29 on 1 rig for different GPUs
in logs
`Jan 26 07:50:58.157 ERRO Plugin cuckatoo_mean_cuda_gtx_31 has errored, device: GeForce GTX 1080 Ti. Reason: Device 9 GPUassert: out of memory /home/travis/build/mimblewimble/grin-miner/cuckoo-miner/src/cuckoo_sys/plugins/cuckoo/src/cuckatoo/mean.cu 429
Jan 26 07:50:58.157 ERRO Plugin cuckatoo_mean_cuda_gtx_31 has errored, device: GeForce GTX 1080 Ti. Reason: Device 9 GPUassert: out of memory /home/travis/build/mimblewimble/grin-miner/cuckoo-miner/src/cuckoo_sys/plugins/cuckoo/src/cuckatoo/mean.cu 429
Jan 26 07:50:58.158 ERRO Plugin cuckatoo_mean_cuda_gtx_31 has errored, device: GeForce GTX 1080 Ti. Reason: Device 9 GPUassert: out of memory /home/travis/build/mimblewimble/grin-miner/cuckoo-miner/src/cuckoo_sys/plugins/cuckoo/src/cuckatoo/mean.cu 429
`
but as you can see on screen, nvidia-smi syas gpu9 in action

**Comment by magican82** [comment]
I think proble is 8gb memory in 1070.
I also can not run it on 1070ti.
1080ti with 11gb mem is ok.

**Comment by PePPeRmix** [comment]
nope, i'm mine at the moment on both cards, just i notice about wrong numeration of GPUs

**Comment by quentinlesceller** [comment]
Closing. Feel free to reopen if this is still relevant.
