### ISSUE TITLE
[BUG] shell script compatibility bug

### ISSUE THREAD

**Issue by james-lim** [mimblewimble/grin-miner#170]
**Describe the bug**

`./install_ocl_plugins.sh` is not executable using zsh. Executing emits following outputs

```zsh
$./install_ocl_plugins.sh
    Finished release [optimized] target(s) in 0.09s
./install_ocl_plugins.sh: 11: [: Linux: unexpected operator
    Finished release [optimized] target(s) in 0.09s
./install_ocl_plugins.sh: 21: [: Linux: unexpected operator
```

**To Reproduce**

1. Use zsh as your env
2. execute ./install_ocl_plugins.sh

**Env**
- zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

**Additional context**
Let me make a PR for this

**Comment by hashmap** [comment]
closed via  #171
