### ISSUE TITLE
mining problems invalid login format

### ISSUE THREAD

**Issue by grinarnevanbelleghemgrin** [mimblewimble/grin-miner#173]
hey, someone knows what to do with this error?

ERROR [hit Enter to hide]: Stratum eu-west-stratum.grinmint.com:4416 invalid login format.

Mining for:           USER         Stratum Server: ---
Connection status:    CONNECTING   Last job in:    14 seconds
Shares (sub/acc/rej):
------------------------------------------------------------------------------------------
GPU 0: GeForce GTX 1070       STARTING       Mining at 0,00 gps            Solutions: 0
       Last Message: 19:24:11:  Waiting for job....

**Comment by quentinlesceller** [comment]
Github is not a support channel. Please go to Gitter grin support.
