### ISSUE TITLE
Miner crashing with rtx 2080ti

### ISSUE THREAD

**Issue by DerTerrieR** [mimblewimble/grin-miner#175]
hi there,

since this morning i am having issues with the miner v1.0.2 on my rtx 2080 ti c31.
i installed all the correct drivers 3 times now with fresh install of ubuntu, nvidia drivers and cuda.

the miner worked on c31 for two days and since today its always crashing after a few minutes.
the screen turn into a matrix like screen and gps goes to zero.

what can be a solution here? should i use an older version of the miner maybe?
![20190201_113151](https://user-images.githubusercontent.com/44715497/52160186-6cc65380-2665-11e9-910a-97b2dd67cee2.jpg)

**Comment by DerTerrieR** [comment]
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0  On |                  N/A |
| 29%   29C    P8    23W / 250W |    342MiB / 10986MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1300      G   /usr/lib/xorg/Xorg                            26MiB |
|    0      1339      G   /usr/bin/gnome-shell                          58MiB |
|    0      1510      G   /usr/lib/xorg/Xorg                           160MiB |
|    0      1642      G   /usr/bin/gnome-shell                          95MiB |
+-----------------------------------------------------------------------------+

**Comment by DerTerrieR** [comment]
is this issue probably coming up because the card has 10.986Gb and not over 11Gb?

**Comment by LuckyX2** [comment]
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 410.48 Driver Version: 410.48 |
> |-------------------------------+----------------------+----------------------+
> | GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
> | Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
> |===============================+======================+======================|
> | 0 GeForce RTX 208... Off | 00000000:01:00.0 On | N/A |
> | 29% 29C P8 23W / 250W | 342MiB / 10986MiB | 1% Default |
> +-------------------------------+----------------------+----------------------+
> 
> +-----------------------------------------------------------------------------+
> | Processes: GPU Memory |
> | GPU PID Type Process name Usage |
> |=============================================================================|
> | 0 1300 G /usr/lib/xorg/Xorg 26MiB |
> | 0 1339 G /usr/bin/gnome-shell 58MiB |
> | 0 1510 G /usr/lib/xorg/Xorg 160MiB |
> | 0 1642 G /usr/bin/gnome-shell 95MiB |
> +-----------------------------------------------------------------------------+

You need to kill those xorg/gnome-shell processes and run CLI/headless. There's not enough room with them running.

**Comment by quentinlesceller** [comment]
Closing. Feel free to reopen if this is still relevant.
