### ISSUE TITLE
grinminer stop to find solutions

### ISSUE THREAD

**Issue by AlexSpain** [mimblewimble/grin-miner#179]
Hashrate change from 12.520257837197056 gps (graphs per second) to Mining: Cuck(at)oo at 11068.545614937264 gps (graphs per second), and miner stop to find solutions, with cpuload=0,
both plugin at use 1card for 31 and 5cards for 29 at same rig

`Feb 04 14:44:34.009 INFO Mining: Cuck(at)oo at 12.520257837197056 gps (graphs per second)`
`Feb 04 14:44:37.004 INFO Status for worker 4638 - Height: 28491, Difficulty: 1, (793/1/12)`
`Feb 04 14:44:37.004 DEBG Received message: {"id":"Stratum","jsonrpc":"2.0","method":"job","params":{"difficulty":4,"height":28491,"job_id":4,"pre_pow":"00010000000000006f4b000000005c5841c00000048d89823160a7fabd232
ff6149bff9e07d0a52357915ceee755330f21118250975bfa21256fd59d897713b933dd46d8d365cbc845ea070e4c3f30ea347e912adc8b76123fefbafcdb95bd21ecc54f6ca95a445aa0322bcabd6c91c8bf6da17df6127606359743e822e7392cb02029163bf183faff
8cb36ae3571f8086a70c9fe39d96e41e15d9b060d31dcd7738a59078552b85af160323d90f02302188498b87441c0fefdd7caa1c4cfae7baf2869bcec82f4c897aec058e39893b91240000000000080814000000000002efa500001f922c07f5e700000384"}}

Feb 04 14:44:37.004 DEBG Received request type: job
Feb 04 14:44:37.004 INFO Got a new job: JobTemplate { height: 28491, job_id: 4, difficulty: 4, pre_pow: "00010000000000006f4b000000005c5841c00000048d89823160a7fabd232ff6149bff9e07d0a52357915ceee755330f21118250975b
fa21256fd59d897713b933dd46d8d365cbc845ea070e4c3f30ea347e912adc8b76123fefbafcdb95bd21ecc54f6ca95a445aa0322bcabd6c91c8bf6da17df6127606359743e822e7392cb02029163bf183faff8cb36ae3571f8086a70c9fe39d96e41e15d9b060d31dcd7
738a59078552b85af160323d90f02302188498b87441c0fefdd7caa1c4cfae7baf2869bcec82f4c897aec058e39893b91240000000000080814000000000002efa500001f922c07f5e700000384" }
Feb 04 14:44:37.011 DEBG Miner received message: ReceivedJob(28491, 3, 4, "00010000000000006f4b000000005c5841ac0000048d89823160a7fabd232ff6149bff9e07d0a52357915ceee755330f21118250975bfa21256fd59d897713b933dd46d8d3
65cbc845ea070e4c3f30ea347e912adc8b76123fefbafcdb95bd21ecc54f6ca95a445aa0322bcabd6c91c8bf6da17df6127606359743e822e7392cb02029163bf183faff8cb36ae3571f8086a703ed6c6282fe370550a9ce1725c1b57b5076d6351af3d3a69f2a4cc1656
6e827498b87441c0fefdd7caa1c4cfae7baf2869bcec82f4c897aec058e39893b91240000000000080814000000000002efa500001f922c07f5e700000384")
Feb 04 14:44:37.011 DEBG Miner received message: ReceivedJob(28491, 4, 4, "00010000000000006f4b000000005c5841c00000048d89823160a7fabd232ff6149bff9e07d0a52357915ceee755330f21118250975bfa21256fd59d897713b933dd46d8d3
65cbc845ea070e4c3f30ea347e912adc8b76123fefbafcdb95bd21ecc54f6ca95a445aa0322bcabd6c91c8bf6da17df6127606359743e822e7392cb02029163bf183faff8cb36ae3571f8086a70c9fe39d96e41e15d9b060d31dcd7738a59078552b85af160323d90f023
02188498b87441c0fefdd7caa1c4cfae7baf2869bcec82f4c897aec058e39893b91240000000000080814000000000002efa500001f922c07f5e700000384")
Feb 04 14:44:37.011 DEBG Mining: Plugin 0 - Device 3 (GeForce GTX 1080 Ti) at Cuck(at)oo31 - Status: OK : Last Graph time: 0.001546371s; Graphs per second: 646.675 - Total Attempts: 4737
Feb 04 14:44:37.011 DEBG Mining: Plugin 1 - Device 0 (GeForce GTX 1060 6GB) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.000453473s; Graphs per second: 2205.203 - Total Attempts: 24733
Feb 04 14:44:37.011 DEBG Mining: Plugin 2 - Device 1 (GeForce GTX 1060 6GB) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.000456131s; Graphs per second: 2192.353 - Total Attempts: 24706
Feb 04 14:44:37.011 DEBG Mining: Plugin 3 - Device 2 (GeForce GTX 1060 6GB) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.000405564s; Graphs per second: 2465.702 - Total Attempts: 24662
Feb 04 14:44:37.011 DEBG Mining: Plugin 4 - Device 4 (GeForce GTX 1060 6GB) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.000447599s; Graphs per second: 2234.143 - Total Attempts: 24664
Feb 04 14:44:37.011 DEBG Mining: Plugin 5 - Device 5 (GeForce GTX 1060 6GB) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.000755019s; Graphs per second: 1324.470 - Total Attempts: 24766
Feb 04 14:44:37.011 INFO Mining: Cuck(at)oo at 11068.545614937264 gps (graphs per second)`

**Comment by quentinlesceller** [comment]
Closing. Feel free to reopen if this is still relevant.
