### ISSUE TITLE
linking with `cc` failed: exit code: 1

### ISSUE THREAD

**Issue by rafaeltokyo** [mimblewimble/grin-miner#182]
i have a problem compile the miner 

linking with `cc` failed: exit code: 1

**Comment by glemercier** [comment]
Please provide more info on which machine you are trying to build on.

**Comment by rafaeltokyo** [comment]
**OS details:**
 Linux version 4.15.0-20-generic (buildd@lgw01-amd64-039) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 (Ubuntu 4.15.0-20.21-generic 4.15.17)

**Machine details:**
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               61
Model name:          Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
Stepping:            4
CPU MHz:             2257.673
CPU max MHz:         3000.0000
CPU min MHz:         500.0000
BogoMIPS:            4789.33
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            4096K
NUMA node0 CPU(s):   0-3

i'm use the OpenCL for miner testing.

**Comment by glemercier** [comment]
Thanks, can you also send more logs of the failing output ?

**Comment by rafaeltokyo** [comment]
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/deadmal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/deadmal/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.0.rcgu.o" "/home/deadmal/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.1.rcgu.o" "/home/deadmal/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.10.rcgu.o" "/home/deadmal/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.11.rcgu.o" "/home/deadmal/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.12.rcgu.o" "/home/deadmal/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.13.rcgu.o" "/home/deadmal/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.14.rcgu.o" "/home/deadmal/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.15.rcgu.o" "/home/deadmal/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.2.rcgu.o" "/home/deadmal/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.3.rcgu.o" "/home/deadmal/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.4.rcgu.o" "/home/deadmal/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.5.rcgu.o" "/home/deadmal/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.6.rcgu.o" "/home/deadmal/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.7.rcgu.o" "/home/deadmal/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.8.rcgu.o" "/home/deadmal/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.9.rcgu.o" "-o" "/home/deadmal/grin-miner/target/release/deps/libocl_cuckaroo.so" "-Wl,--version-script=/tmp/rustc05O1uG/list" "/home/deadmal/grin-miner/target/release/deps/ocl_cuckaroo.3a288qk8ou1nl0zg.rcgu.o" "-Wl,--gc-sections" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/deadmal/grin-miner/target/release/deps" "-L" "/home/deadmal/grin-miner/target/release/build/backtrace-sys-3bb8a31414250770/out" "-L" "/home/deadmal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/deadmal/grin-miner/target/release/deps/libocl-2b6ca7e72de04a46.rlib" "/home/deadmal/grin-miner/target/release/deps/libqutex-2877175ff9d16c53.rlib" "/home/deadmal/grin-miner/target/release/deps/libcrossbeam-ae24da8fd5ab9e14.rlib" "/home/deadmal/grin-miner/target/release/deps/libocl_core-bd1328ed4b3f181a.rlib" "/home/deadmal/grin-miner/target/release/deps/libcl_sys-8e75588e8619941c.rlib" "/home/deadmal/grin-miner/target/release/deps/libocl_core_vector-026f0515ba5d20c4.rlib" "/home/deadmal/grin-miner/target/release/deps/libnum-99be027e11663d36.rlib" "/home/deadmal/grin-miner/target/release/deps/libnum_rational-e6972cae3401919e.rlib" "/home/deadmal/grin-miner/target/release/deps/libnum_bigint-ff24e3d4d9a721d3.rlib" "/home/deadmal/grin-miner/target/release/deps/librand-f58ac22ae7bdb73b.rlib" "/home/deadmal/grin-miner/target/release/deps/libnum_iter-cc8373252e5b44b7.rlib" "/home/deadmal/grin-miner/target/release/deps/libnum_integer-f5b487922e4458ef.rlib" "/home/deadmal/grin-miner/target/release/deps/libnum_complex-6becc21e1b860a3a.rlib" "/home/deadmal/grin-miner/target/release/deps/librustc_serialize-3fd725ad7fdcef8b.rlib" "/home/deadmal/grin-miner/target/release/deps/libenum_primitive-e671d84a8a53afa6.rlib" "/home/deadmal/grin-miner/target/release/deps/libnum_traits-daad0bed6aa3e3dc.rlib" "/home/deadmal/grin-miner/target/release/deps/libbitflags-adf99be71dc8e804.rlib" "/home/deadmal/grin-miner/target/release/deps/libfailure-8708e6e9ea42ccba.rlib" "/home/deadmal/grin-miner/target/release/deps/libbacktrace-7783e5e7ffe92531.rlib" "/home/deadmal/grin-miner/target/release/deps/libbacktrace_sys-655c597a1c2fde81.rlib" "/home/deadmal/grin-miner/target/release/deps/librustc_demangle-50b34a035279142c.rlib" "/home/deadmal/grin-miner/target/release/deps/libcfg_if-ca1d65f5ee31c6bc.rlib" "/home/deadmal/grin-miner/target/release/deps/libfutures-98af041b5ca94008.rlib" "/home/deadmal/grin-miner/target/release/deps/libnum_traits-7361744d4501fa73.rlib" "/home/deadmal/grin-miner/target/release/deps/libhashbrown-61423d94bd47c5c6.rlib" "/home/deadmal/grin-miner/target/release/deps/libscopeguard-c10404cc72a7b9c1.rlib" "/home/deadmal/grin-miner/target/release/deps/libgrin_miner_plugin-a232dca56dbfe95d.rlib" "/home/deadmal/grin-miner/target/release/deps/libserde_json-e1fb8a333dfffe1e.rlib" "/home/deadmal/grin-miner/target/release/deps/libitoa-e7f370e1dd474f2d.rlib" "/home/deadmal/grin-miner/target/release/deps/libryu-fc5b84abae0f552f.rlib" "/home/deadmal/grin-miner/target/release/deps/liblibc-3a2d5840f9bc6431.rlib" "/home/deadmal/grin-miner/target/release/deps/libbyteorder-03ac63d0c1e7d146.rlib" "/home/deadmal/grin-miner/target/release/deps/libserde-d1d6957f1e4c0d27.rlib" "/home/deadmal/grin-miner/target/release/deps/libbyteorder-4c669adbb7f95051.rlib" "/home/deadmal/grin-miner/target/release/deps/libblake2_rfc-4bf72a57424090c8.rlib" "/home/deadmal/grin-miner/target/release/deps/libconstant_time_eq-4b817e1b698abc38.rlib" "/home/deadmal/grin-miner/target/release/deps/libarrayvec-f9f7461fe1c554a5.rlib" "/home/deadmal/grin-miner/target/release/deps/libnodrop-f21ba50b12025db4.rlib" "-Wl,--start-group" "/home/deadmal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-dd4752c70d4ce71d.rlib" "/home/deadmal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-e04840eda0100e05.rlib" "/home/deadmal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-16bfb4d182748e63.rlib" "/home/deadmal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-185d9b81685a2f08.rlib" "/home/deadmal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-4806247fe4c34e64.rlib" "/home/deadmal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-879310dc3b96af61.rlib" "-Wl,--end-group" "/home/deadmal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-d0572f7a936161bf.rlib" "-Wl,-Bdynamic" "-lOpenCL" "-lOpenCL" "-lutil" "-lutil" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil" "-shared"
  = note: /usr/bin/ld: cannot find -lOpenCL
          /usr/bin/ld: cannot find -lOpenCL
          collect2: error: ld returned 1 exit status

**Comment by rafaeltokyo** [comment]
thank you, i will going install the driver.
