### ISSUE TITLE
Failed assertion causes grin-miner to crash when cuckatoo_mean_cuda_rtx_31 plugin loaded

### ISSUE THREAD

**Issue by dyslexicon** [mimblewimble/grin-miner#183]
@tromp 
In `grin-miner/cuckoo-miner/src/cuckoo_sys/plugins/cuckoo/src/cuckatoo/mean.cu`, 

line 510
`assert(bufferSize - sizeB >= sizeB / (tp.expand==2 ? 1 : 2)); // ensure enough space for Round 1, / 2 is for 0.296 / 0.632 without expansion
`

fails and causes grin miner to crash. 

If commented out, the miner runs, though about half it's shares are rejected.

**Comment by tromp** [comment]
It crashes becasue the chosen parameters for NRB1, NEPS_A/B, and expand are inconsistent.

Did you make any changes to grin-miner/cuckoo-miner/src/cuckoo_sys/plugins/CMakeLists.txt 
 ? Is it compiled with "-DNRB1=26 -DNEPS_A=133 -DNEPS_B=85 -DPART_BITS=0 -DEDGEBITS=31" ?

Did you set expand = 2 in grin-miner.toml?

**Comment by dyslexicon** [comment]
I didn't modify anything except `Cargo.toml` (to build the cuda plugins) and `expand = 2` is set in `grin-miner.toml` as it was by default.

**Comment by dyslexicon** [comment]
Yea, just cloned again and built from source, modifying nothing, and same result. Running `nvidia-415.27-4` and `cuda-10.0.130-2` on Arch linux.

**Comment by tromp** [comment]
> I didn't modify anything except Cargo.toml (to build the cuda plugins) and expand = 2 is set in grin-miner.toml as it was by default.

That should be expand=3 for the _rtx_ and _gtx_ plugins.
But https://github.com/mimblewimble/grin-miner/blob/master/grin-miner.toml
shows the setting to be commented out. Did you perhaps remove the
initial hash sign?

Could you set it to 3 and try again?

**Comment by dyslexicon** [comment]
I see @yeastplume just fixed it: https://github.com/mimblewimble/grin-miner/commit/da6cb2c6784f70260333263ee596a5a4fbb5e95f. `expand = 3` is working for me, no failed assertion, no rejected shares. 👍
