### ISSUE TITLE
INFO Mining: Cuck(at)oo at 0 gps (graphs per second)

### ISSUE THREAD

**Issue by earlystareyes** [mimblewimble/grin-miner#184]
When I use CPU for mining,  with all the default setting, the Mining Status is Starting miner and awaiting first graph time..
grin-miner.log shows: 
**Feb 06 15:41:58.013 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Feb 06 15:42:01.014 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0**

It seems start mining now, but there's no GPS...how to deal with it?

**Comment by earlystareyes** [comment]
<img width="1140" alt="2019-02-06 15 55 27" src="https://user-images.githubusercontent.com/42319667/52327608-ac0af080-2a27-11e9-8840-aa2832f67efa.png">

**Comment by glemercier** [comment]
What GPU are you trying to mine on? Also does it have at least 8GB of RAM?

**Comment by hashmap** [comment]
do you run `grin wallet listen`?

**Comment by quentinlesceller** [comment]
Closing. Feel free to reopen if this is still relevant.
