### ISSUE TITLE
grin-miner crash with f2pool after few hours run.

### ISSUE THREAD

**Issue by smartbitcoin** [mimblewimble/grin-miner#187]
Thread 'client_controller' panicked with message:
"called `Result::unwrap()` on an `Err` value: Error("trailing characters", line: 1, column: 2)"
See grin.log for further details.
Feb 08 02:28:27.037 ERRO
thread 'client_controller' panicked at 'called `Result::unwrap()` on an `Err` value: Error("trailing characters", line: 1, column: 2)': libcore/result.rs:1009stack backtrace:
   0:     0x55c015adc57d - backtrace::backtrace::trace::h6a895d5d279a8d2f
   1:     0x55c015adb792 - <backtrace::capture::Backtrace as core::default::Default>::default::h03a8d770395d927e
   2:     0x55c015adb809 - backtrace::capture::Backtrace::new::h2eb1c11c92f206be
   3:     0x55c015ab0360 - grin_miner_util::logger::send_panic_to_log::{{closure}}::h39a4be52b87a956e
   4:     0x55c015b08e96 - std::panicking::rust_panic_with_hook::hde420d6fd4455550
                        at libstd/panicking.rs:480
   5:     0x55c015b089e1 - std::panicking::continue_panic_fmt::h8f394f3c578bcc76
                        at libstd/panicking.rs:390
   6:     0x55c015b088c5 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:     0x55c015b4f58c - core::panicking::panic_fmt::hca5dc4e8b320bc56
                        at libcore/panicking.rs:77
   8:     0x55c015a03dde - core::result::unwrap_failed::h1e12d6d1ef2a15d4
   9:     0x55c0159b323f - grin_miner::client::Controller::run::he099667b18f63551
  10:     0x55c0159cf223 - std::sys_common::backtrace::__rust_begin_short_backtrace::h09e33a5aaff02580
  11:     0x55c0159e03a8 - std::panicking::try::do_call::h6ff33c1e1448a207
  12:     0x55c015b18f29 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  13:     0x55c0159eee97 - <F as alloc::boxed::FnBox<A>>::call_box::h4b595e9014bd3345
  14:     0x55c015b062ed - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h9d902c911a417e39
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h44127e03e78ca137
                        at libstd/sys_common/thread.rs:24
  15:     0x55c015af7605 - std::sys::unix::thread::Thread::new::thread_start::h8f17b97f2223146c
                        at libstd/sys/unix/thread.rs:90
  16:     0x7f6d6cdee6b9 - start_thread
  17:     0x7f6d6c90e41c - clone
  18:                0x0 - <unknown>

**Comment by lukaszmatczak** [comment]
Hello
I have similar error:
```Feb 12 07:33:06.194 ERRO
thread 'client_controller' panicked at 'called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 2, column: 0)': src/libcore/result.rs:1009stack backtrace:
   0:     0x55fe605a4d9d - backtrace::backtrace::trace::h16f4d19e5ed7ab6a
   1:     0x55fe605a3ec2 - <backtrace::capture::Backtrace as core::default::Default>::default::h8fc4747ef7529ae8
   2:     0x55fe6056f400 - grin_miner_util::logger::send_panic_to_log::{{closure}}::h2e69af416f76170f
   3:     0x55fe605d11d9 - std::panicking::rust_panic_with_hook::h8cbdfe43764887be
                        at src/libstd/panicking.rs:495
   4:     0x55fe605d0c81 - std::panicking::continue_panic_fmt::h3d3c5a833c00a5e1
                        at src/libstd/panicking.rs:398
   5:     0x55fe605d0b65 - rust_begin_unwind
                        at src/libstd/panicking.rs:325
   6:     0x55fe605e6f9c - core::panicking::panic_fmt::h4d67173bc68f6d5a
                        at src/libcore/panicking.rs:95
   7:     0x55fe604c5f7e - core::result::unwrap_failed::h0d2852a22d17c6cc
   8:     0x55fe604d3a22 - grin_miner::client::Controller::run::h0761260341ec94bf
   9:     0x55fe604984d3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0e0804adedc74d6d
  10:     0x55fe60499325 - std::panicking::try::do_call::hd3928d938db05247
  11:     0x55fe605e0ac9 - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:102
  12:     0x55fe604a8fd7 - <F as alloc::boxed::FnBox<A>>::call_box::hcce65d9205bce626
  13:     0x55fe605d49ad - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::hece536cf07b94f8d
                        at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/liballoc/boxed.rs:683
                         - std::sys_common::thread::start_thread::h9605a7df0f911844
                        at src/libstd/sys_common/thread.rs:24
                         - std::sys::unix::thread::Thread::new::thread_start::hca8e72c41fa9d291
                        at src/libstd/sys/unix/thread.rs:90
  14:     0x7fd0f969b5a9 - start_thread
  15:     0x7fd0f91b9cbe - __clone
  16:                0x0 - <unknown>
```

**Comment by perry-mitchell** [comment]
@lukaszmatczak Yours seems to be more closely related to #190, as your error is an EOF one and @smartbitcoin's is related to trailing characters.

**Comment by quentinlesceller** [comment]
Closing. Feel free to reopen if this is still relevant.
