### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:355:21 note: Run with `RUST_BACKTRACE=1` for a backtrace

### ISSUE THREAD

**Issue by Lalit15** [mimblewimble/grin-miner#189]
I am running grin on Google cloud and I am getting error the above error when i run the grin-miner command from grin-miner/target/debug folder. I am not sure why this error is coming. Kindly help me in resolving this error and run grin miner successfully.

Also, as per the documentation it is mentioned that we should try to run the grin-miner command from grin-miner/target folder. But i run the command from target folder i get the error as "**-bash: ./grin-miner: No such file or directory**".
The reason being that grin-miner file is being generated in the debug folder and not target folder and hence i think the documentation needs to be updated for that.

**Comment by hashmap** [comment]
Assuming you have grin-miner in `~/grin-miner` folder
```
$ cd ~/grin-miner
$ cargo build
$ ./target/debug/grin-miner
```
you need to run it from the folder with `grin-miner.toml`
Also I'd recommend to use binary release if it works for you.

**Comment by Lalit15** [comment]
Thanks @hashmap...your approach worked
will see how effective is the minning
