### ISSUE TITLE
Windows Compiling (Working on getting it to work)

### ISSUE THREAD

**Issue by MaynardMiner** [mimblewimble/grin-miner#191]
I have been working hard on trying to get this miner to compile in windows- If I do so, I plan to submit m work. These are the things I have found so far that can be done (I don't know if they are the best thing to do).

1.) Pancurses
     It seems pancurses will work in windows, so far setting it as backend for curses seems to work, and uses it doesn't generate errors regarding it while compiling. I have fully completed a compile yet to know if it is successful.

2.) Pthreads
    To my limited knowledge, if you manually load in pthreads-w32 lib, and specify it in lieu of pthreads.h, It seems like it starts reducing compile errors , but there are still errors..However, there are still little code fixes which I am trying to see if I can implement to make it work. Has anyone considered maybe switching the codebase to boost? I read that it performs better anyways, but I'm not too familiar with both to have a serious grasp on it. I was going to look into that.

3.) xargo
    xargo seems to resolve a lot of std issues, but not all of them. It seems to be a good start, using xargo build instead of cargo. However, I have to make some small changes to make it work, which I will post if I ever get a compiled version.

4.) compile flags.
     I am still testing compile flags, but most of the flags set right now seem to be ignored when attempting to compile. I am working on researching and changing them to suit Windows.

I have reached close to about 85% of the project being successfully compiled for a test run. At this point I am down to getting the plugins to compile.

I post this, as I see nobody else immediately attempting to figure out how to get it to work in Windows, I figure others may have suggestions which may assist.

**Comment by yeastplume** [comment]
It should be possible to get grin-miner itself working on windows without having to introduce 3rd party libraries for threading or non-standard tools (and most certainly not boost,) but the reason nobody is working on this at the moment is that the solvers themselves are completely linux pthread bound. They would need to be reworked quite a bit to get them working on windows, and given there are community alternatives for windows mining, it doesn't seem a priority at the moment.

**Comment by MaynardMiner** [comment]
Actually, there is currently no miner for AMD that works with nicehash windows. I have users begging me to make something happen, as I was able to compile the linux version for AMD nicehash support. So I have been trying to port over to windows. It doesn't seem the windows versions plan to support it anytime soon.

**Comment by MaynardMiner** [comment]
Plus, just in general, it would be nice to contribute to a cool project, and great job with what you have done so far.

**Comment by quentinlesceller** [comment]
I think with latest PR #246 this should compile on Windows. However I had some issues with cmake locally? I'll see if I can setup the CI with Windows later.

**Comment by quentinlesceller** [comment]
I'm closing that one. I believe it is possible to compile it for windows now.
