### ISSUE TITLE
CL_INVALID_WORK_GROUP_SIZE(-54)

### ISSUE THREAD

**Issue by crypthusiast0** [mimblewimble/grin-miner#195]
I am running a Mac Pro with AMD FirePro D500 Dual GPUs. I get this: 
`Status error code: CL_INVALID_WORK_GROUP_SIZE (-54)` What should I do about this?

**Comment by timetoseek** [comment]
@crypthusiast0 I believe the issue may be similar to the one I have, please see link below...
https://github.com/mimblewimble/grin-miner/issues/199#issue-418456383

**Comment by hashmap** [comment]
@crypthusiast0  would you mind to post `clinfo` output to #199? I'm closing this one as a duplicate, it seems we have more info there
