### ISSUE TITLE
Segmentation fault on macOS Sierra and High Sierra

### ISSUE THREAD

**Issue by photis** [mimblewimble/grin-miner#2]
After about 15 minutes grin-miner, connected to a remote stratum server over an unstable internet connection, crashes with a segmentation fault. It happens every time. Also tested on another MBP running a clean version of Sierra with same result.

1) macOS High Sierra 10.13.4 (17E202), MacBook Pro (Retina, 15-inch, Mid 2015), 2,5 GHz Intel Core i7, 16 GB 1600 MHz DDR3

2) macOS Sierra 10.12.6 (16G1314), MacBook Pro (Retina, 15-inch, Early 2013), 2.4 GHz Intel Core i7, 8 GB 1600 MHz DDR3

[grin-miner_2018-05-03-190344_hermes_crash.txt](https://github.com/mimblewimble/grin-miner/files/1972130/grin-miner_2018-05-03-190344_hermes_crash.txt)

**Comment by photis** [comment]
Second follow-up:
I tested with a locally run grin stratum server on the 2nd MBP, and a local miner on the same MBP. In this setup, it is also _only_ the `lean_cpu` miner that runs without problems. Both `mean_cpu` and `mean_compat_cpu` return a segmentation fault after 15-20 minutes running, same as with a remote stratum server, as described above. That means we can rule out that a flaky communication channel is to blame.

**Comment by photis** [comment]
Third follow-up:
After running for 24 hours, grin-miner with lean_cpu connected to a local stratum server also terminated with a Segmentation Fault.

macOS Sierra 10.12.6 (16G1314), MacBook Pro (Retina, 15-inch, Early 2013), 2.4 GHz Intel Core i7, 8 GB 1600 MHz DDR3

**Comment by andybellenie** [comment]
I'm seeing the same issue on 2012 MBP with High Sierra.

**Comment by garyyu** [comment]
also see `Segmentation fault` on mac air / macbook / mac pro.

**Comment by garyyu** [comment]
@photis, how did you get your backtrace?  I run it by `$ RUST_BACKTRACE=1 ./target/debug/grin-miner` but when `Segmentation fault: 11` happen, I can't see the backtrace.

**Comment by photis** [comment]
Look under “User Reports” (in left column) in standard macOS Console.app

**Comment by garyyu** [comment]
@photis  @andybellenie   Could you please take the latest version and test it again? to confirm this fix also works for your MBP. Thanks~

**Comment by photis** [comment]
@garyyu On it now, took some time because I'm on the move again and had some trouble convincing the owner of the router I'm connecting to to let me forward the necessary ports. Will keep you posted.

**Comment by andybellenie** [comment]
Seems fixed, thanks!

**Comment by photis** [comment]
Both executables were build on the running MBP. I hadn't done a `cargo clean` prior to the `cargo build --release`, will do that now and let you know the result.

**Comment by photis** [comment]
Sorry it took so long, there were some incidents that required my attention elsewhere. I did as you instructed and running grin-miner with `mean_cpu` still results in an `illegal instruction` error. The log file doesn't report on this, it's the TUI that shows that message. Log file below

```
May 28 22:12:24.748 INFO This is Grin-Miner version 0.2.0 (git 707ed7d), built for x86_64-apple-darwin by rustc 1.26.0 (a77568041 2018-05-07).
May 28 22:12:24.749 DEBG Built with profile "release", features "" on Mon, 28 May 2018 17:27:25 GMT.
May 28 22:12:25.753 WARN Connection Status: Connected to Grin server at 127.0.0.1:13416.
May 28 22:12:25.858 DEBG sending request: {"id":"0","jsonrpc":"2.0","method":"getjobtemplate","params":null}
May 28 22:12:26.064 DEBG Received message: {"id":"1","jsonrpc":"2.0","method":"getjobtemplate","result":"{\"height\":89081,\"difficulty\":1,\"pre_pow\":\"00010000000000015bf9b3d0c25d217ca4a03284cc63e0c53440113912ef13f17390afe52ab45e50f4f5000000005b0c547e000000000001dfa7a20c11610e0223c225102d768bc75f7ac822c4b62525701ef4f09f74d7d08cb7c7a31b8b85ed19042f24a7271c74ce87592d90d9a7eb9efea18b05283ec5ed2c8e037f605a02eb2885a041e343cf31498d3820b570865958ff87c790df3e6537b15a750103ca95180bb23750215b28707a55f339dd29b5d63155f9f6def2fec2\"}","error":null}

May 28 22:12:26.064 DEBG Received response with id: 1
May 28 22:12:26.064 INFO Got a job at height 89081 and difficulty 1
May 28 22:12:26.097 DEBG Miner received message: ReceivedJob(89081, 1, "00010000000000015bf9b3d0c25d217ca4a03284cc63e0c53440113912ef13f17390afe52ab45e50f4f5000000005b0c547e000000000001dfa7a20c11610e0223c225102d768bc75f7ac822c4b62525701ef4f09f74d7d08cb7c7a31b8b85ed19042f24a7271c74ce87592d90d9a7eb9efea18b05283ec5ed2c8e037f605a02eb2885a041e343cf31498d3820b570865958ff87c790df3e6537b15a750103ca95180bb23750215b28707a55f339dd29b5d63155f9f6def2fec2")
May 28 22:12:26.097 DEBG Mining Cuckoo30 for height: 89081
May 28 22:12:26.117 INFO Cuckoo plugin 0 - /Users/photis/Projects/mimble/grin-miner/target/release/plugins/mean_cpu_30.cuckooplugin
May 28 22:12:26.117 DEBG Cuckoo Plugin 0: Setting mining parameter NUM_THREADS to 1 on Device 0
May 28 22:12:27.049 DEBG Mining: Plugin 0 - Device 0 (CPU) Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
May 28 22:12:27.049 INFO Mining: Cuckoo30 at 0 gps (graphs per second)
```
...and it stops just there. No other lines are output.

The log from macOS Console.app is here:
[grin-miner_2018-05-28-221228_janus.crash.txt](https://github.com/mimblewimble/grin-miner/files/2045981/grin-miner_2018-05-28-221228_janus.crash.txt)

**Comment by garyyu** [comment]
Could you please try `mean_compat_cpu`? Thanks.

**Comment by garyyu** [comment]
Oh, I just go back to history and saw you had tested  `mean_compat_cpu` with NUM_THREADS=1 for almost 12 hours. That means this problem has already been fixed, you can set NUM_THREADS=4 or 8, as many as your CPU cores number.   
`mean_cpu` can only be used for some new CPU, your MacBook Pro (Retina, 15-inch, Early 2013) can't use this option. 
Thanks again for your test. You can close this issue if no other questions.

**Comment by photis** [comment]
Alright, glad it helped and thanks for fixing it.
