### ISSUE TITLE
Linux Binary missing ocl_cuckaroo plugin

### ISSUE THREAD

**Issue by timetoseek** [mimblewimble/grin-miner#202]
It is not possible to install the "ocl_cuckaroo" plugin if you download the Linux binary... 
The instructions in "grin-miner.toml" say to build them, but it is not possible to do so.  Please include them in the binary versions. Thank you!

**Comment by quentinlesceller** [comment]
There is an `install_ocl_plugins.sh` to build them. I'm going to close that one since we are not going to ship the `ocl_cuckaroo` plugin because of CI issues.
