### ISSUE TITLE
help with json rpc getting code 32500

### ISSUE THREAD

**Issue by enzosrock** [mimblewimble/grin-miner#217]
here is the log file for the Grin miner v1.0.2 that i am having issues with. Im running on linux mint and an AMD R9 GPU
 Ive tried searching around and everything is just a dead end. any advice? thanks, E

Jul 02 19:13:52.652 INFO This is Grin-Miner version 1.0.2 (git v1.0.2), built for x86_64-unknown-linux-gnu by rustc 1.31.1 (b6c32da9b 2018-12-18).
Jul 02 19:13:52.652 DEBG Built with profile "release", features "CURSIVE, DEFAULT, OCL_CUCKAROO, OCL_CUCKATOO, OPENCL, TUI" on Thu, 17 Jan 2019 09:43:20 GMT.
Jul 02 19:13:52.652 DEBG Starting solvers
Jul 02 19:13:52.652 DEBG No mining plugin dir provided by config. Using default plugin dir: "/home/user/Desktop/grin-miner-v1.0.2/plugins"
Jul 02 19:13:52.652 DEBG Loading miner plugin: /home/user/Desktop/grin-miner-v1.0.2/plugins/ocl_cuckatoo.cuckooplugin
Jul 02 19:13:52.652 DEBG Loading miner plugin: /home/user/Desktop/grin-miner-v1.0.2/plugins/ocl_cuckatoo.cuckooplugin
Jul 02 19:13:53.827 WARN Connection Status: Connected to Grin server at us-east-stratum.grinmint.com:4416.
Jul 02 19:13:53.837 DEBG sending request: {"id":"0","jsonrpc":"2.0","method":"getjobtemplate","params":null}
Jul 02 19:13:54.008 DEBG Received message: {"id":"0","jsonrpc":"2.0","method":"getjobtemplate","error":{"code":-32500,"message":"login first"}}
Jul 02 19:13:54.009 DEBG Received response with id: 0
Jul 02 19:13:54.009 ERRO Failed to get a job template: RpcError { code: -32500, message: "login first" }
Jul 02 19:13:54.009 ERRO Error reading message: ConnectionError("broken pipe")
Jul 02 19:13:54.053 DEBG Miner received message: StopJob
Jul 02 19:13:54.053 DEBG Stopping jobs

here is the open cl tmol
```

# lean OpenCL supports both NVidia and AMD
# very slow but requires ~ 3GB of RAM
# to install run ./install_ocl_plugins.sh script
[[mining.miner_plugin_config]]
plugin_name = "ocl_cuckatoo"
[mining.miner_plugin_config.parameters]
# 0 for default, 1 for AMD, 2 for NVidia, specify if you have
# cards from both vendors
platform = 1
# ID withing the platform
device = 1
edge_bits = 31
```

**Comment by quentinlesceller** [comment]
Hi, you need to provide a login in your configuration file. This is not grin-miner related but a requirement by Grinmint.

**Comment by enzosrock** [comment]
I had the logon information in the toml file like email, and pswd at the top and the opencl conf Is at the bottom.

**Comment by enzosrock** [comment]
.

**Comment by quentinlesceller** [comment]
Hi @enzosrock this is not a grin-miner related issue so it doesn't belong here. Make sure you remove the `#`  in front of the line.
If you wish to receive support for this send an email at grinmint-support@blockcypher.com
