### ISSUE TITLE
Meaner Cuda Plugin stops mining after a few seconds

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin-miner#24]
See https://pastebin.com/yexYpPbQ. The miner continue to process the messages but do not actually mine with meaner Cuda.

**Comment by quentinlesceller** [comment]
https://github.com/mimblewimble/grin-miner/commit/5b177ab8eba45fe84406089050db9c1fcfb345c5 seems to work.

**Comment by quentinlesceller** [comment]
https://github.com/mimblewimble/cuckoo-miner/pull/18 fix this issue. Leaving this issue open until merge.

**Comment by illera88** [comment]
This should be closed
