### ISSUE TITLE
Cuckaroom CPU and OpenCL implementations?

### ISSUE THREAD

**Issue by dagonharett** [mimblewimble/grin-miner#240]
AFAICT only the Cuckaroom CUDA implementation is currently working on master (28f39532a5879a49bfed81d9e27aa59ccb773597). Since [Hardfork2](https://github.com/mimblewimble/grin/pull/3136) is now live, are there any plans to finish both the CPU and OpenCL implementations?

Upon building grin-miner and the OpenCL plugins I got `cuckaroo` and `cuckarood` plugins for the CPU and `cuckaroo` for OpenCL. As expected, they all produce invalid shares on a synced grin node:
```
ERROR grin_servers::mining::stratumserver - (Server ID: 0) Failed to validate share at height 529882, hash 4af5931a5bfa, edge_bits 29, nonce 6745532596357350798, job_id 3. Err(Error { inner:Verification Error: endpoints don't match up })
```

It just feels strange that there are no official CPU and OpenCL implementations. Was all the testing done with just the CUDA implementation?

**Comment by quentinlesceller** [comment]
Hi @dagonharett, yes the testing was done with the CUDA solver.
I don't personally have the bandwidth to work on an OpenCL solver. So if you are able to implement it, that'd more than welcome (or if you know anyone able to).

**Comment by dagonharett** [comment]
Closing this issue as Cuckaroom is going to be phased out pretty soon. CPU and OpenCL implementations would now be useful for Cuckarooz, check #250.
