### ISSUE TITLE
error: linking with `cc` failed: exit code: 1

### ISSUE THREAD

**Issue by OlegWebmaster** [mimblewimble/grin-miner#245]
When I run the ./install_ocl_plugins.sh command according to the instructions, I get errors. The first one is:
`error: linking with `cc` failed: exit code: 1`

**Full text:**
`$ ./install_ocl_plugins.sh
warning: use of deprecated item 'libc::uint32_t': Use u32 instead.
  --> plugin/src/lib.rs:55:2
   |
55 |     uint32_t,             // header length
   |     ^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: use of deprecated item 'libc::uint64_t': Use u64 instead.
  --> plugin/src/lib.rs:56:2
   |
56 |     uint64_t,             // nonce
   |     ^^^^^^^^

warning: use of deprecated item 'libc::uint32_t': Use u32 instead.
  --> plugin/src/lib.rs:57:2
   |
57 |     uint32_t,             // range
   |     ^^^^^^^^

warning: use of deprecated item 'libc::uint32_t': Use u32 instead.
  --> plugin/src/lib.rs:60:6
   |
60 | ) -> uint32_t;
   |      ^^^^^^^^

warning: use of deprecated item 'libc::uint32_t': Use u32 instead.
  --> plugin/src/lib.rs:78:16
   |
78 |     pub nthreads: uint32_t,
   |                   ^^^^^^^^

warning: use of deprecated item 'libc::uint32_t': Use u32 instead.
  --> plugin/src/lib.rs:80:14
   |
80 |     pub ntrims: uint32_t,
   |                 ^^^^^^^^

warning: use of deprecated item 'libc::uint32_t': Use u32 instead.
   --> plugin/src/lib.rs:152:17
    |
152 |     pub device_id: uint32_t,
    |                    ^^^^^^^^

warning: use of deprecated item 'libc::uint32_t': Use u32 instead.
   --> plugin/src/lib.rs:154:17
    |
154 |     pub edge_bits: uint32_t,
    |                    ^^^^^^^^

warning: use of deprecated item 'libc::uint32_t': Use u32 instead.
   --> plugin/src/lib.rs:164:18
    |
164 |     pub iterations: uint32_t,
    |                     ^^^^^^^^

warning: use of deprecated item 'libc::uint64_t': Use u64 instead.
   --> plugin/src/lib.rs:166:23
    |
166 |     pub last_start_time: uint64_t,
    |                          ^^^^^^^^

warning: use of deprecated item 'libc::uint64_t': Use u64 instead.
   --> plugin/src/lib.rs:168:21
    |
168 |     pub last_end_time: uint64_t,
    |                        ^^^^^^^^

warning: use of deprecated item 'libc::uint64_t': Use u64 instead.
   --> plugin/src/lib.rs:170:26
    |
170 |     pub last_solution_time: uint64_t,
    |                             ^^^^^^^^

warning: use of deprecated item 'libc::uint64_t': Use u64 instead.
   --> plugin/src/lib.rs:233:10
    |
233 |     pub id: uint64_t,
    |             ^^^^^^^^

warning: use of deprecated item 'libc::uint64_t': Use u64 instead.
   --> plugin/src/lib.rs:235:13
    |
235 |     pub nonce: uint64_t,
    |                ^^^^^^^^

warning: use of deprecated item 'libc::uint64_t': Use u64 instead.
   --> plugin/src/lib.rs:237:14
    |
237 |     pub proof: [uint64_t; PROOFSIZE],
    |                 ^^^^^^^^

   Compiling ocl_cuckatoo v1.0.2 (/tmp/grin-miner/ocl_cuckatoo)
warning: use of deprecated item 'libc::uint32_t': Use u32 instead.
  --> ocl_cuckatoo/src/lib.rs:75:17
   |
75 |     header_length: uint32_t,
   |                    ^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: use of deprecated item 'libc::uint64_t': Use u64 instead.
  --> ocl_cuckatoo/src/lib.rs:76:9
   |
76 |     nonce: uint64_t,
   |            ^^^^^^^^

warning: use of deprecated item 'libc::uint32_t': Use u32 instead.
  --> ocl_cuckatoo/src/lib.rs:77:10
   |
77 |     _range: uint32_t,
   |             ^^^^^^^^

warning: use of deprecated item 'libc::uint32_t': Use u32 instead.
  --> ocl_cuckatoo/src/lib.rs:80:6
   |
80 | ) -> uint32_t {
   |      ^^^^^^^^

warning: method is never used: `nodes`
   --> ocl_cuckatoo/src/finder.rs:222:2
    |
222 |     fn nodes(&self) -> impl Iterator<Item = &u32> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "/tmp/grin-miner/target/release/deps/ocl_cuckatoo.ocl_cuckatoo.esmlssux-cgu.0.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckatoo.ocl_cuckatoo.esmlssux-cgu.1.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckatoo.ocl_cuckatoo.esmlssux-cgu.10.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckatoo.ocl_cuckatoo.esmlssux-cgu.11.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckatoo.ocl_cuckatoo.esmlssux-cgu.12.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckatoo.ocl_cuckatoo.esmlssux-cgu.13.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckatoo.ocl_cuckatoo.esmlssux-cgu.14.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckatoo.ocl_cuckatoo.esmlssux-cgu.15.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckatoo.ocl_cuckatoo.esmlssux-cgu.2.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckatoo.ocl_cuckatoo.esmlssux-cgu.3.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckatoo.ocl_cuckatoo.esmlssux-cgu.4.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckatoo.ocl_cuckatoo.esmlssux-cgu.5.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckatoo.ocl_cuckatoo.esmlssux-cgu.6.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckatoo.ocl_cuckatoo.esmlssux-cgu.7.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckatoo.ocl_cuckatoo.esmlssux-cgu.8.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckatoo.ocl_cuckatoo.esmlssux-cgu.9.rcgu.o" "-o" "/tmp/grin-miner/target/release/deps/libocl_cuckatoo.so" "-Wl,--version-script=/tmp/rustcKJB2cT/list" "/tmp/grin-miner/target/release/deps/ocl_cuckatoo.4k5bg65cee4a1ds4.rcgu.o" "-Wl,--gc-sections" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/tmp/grin-miner/target/release/deps" "-L" "/tmp/grin-miner/target/release/build/backtrace-sys-c06179d02ff280b6/out" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/grin-miner/target/release/deps/libocl-6ffa61d4f4954378.rlib" "/tmp/grin-miner/target/release/deps/libqutex-6dffd7181766d36a.rlib" "/tmp/grin-miner/target/release/deps/libcrossbeam-a33363128528f52e.rlib" "/tmp/grin-miner/target/release/deps/libcrossbeam_queue-6769d25ad3310111.rlib" "/tmp/grin-miner/target/release/deps/libcrossbeam_channel-1d882d4c1ef5456e.rlib" "/tmp/grin-miner/target/release/deps/libcrossbeam_deque-a6a5b9a03ea16c2a.rlib" "/tmp/grin-miner/target/release/deps/libcrossbeam_epoch-54c7b6b58321d000.rlib" "/tmp/grin-miner/target/release/deps/libscopeguard-aa02c8d466759377.rlib" "/tmp/grin-miner/target/release/deps/libmemoffset-fd63a4603bd61145.rlib" "/tmp/grin-miner/target/release/deps/libcrossbeam_utils-4cd75011f8777a01.rlib" "/tmp/grin-miner/target/release/deps/liblazy_static-0d6fc211b0b9e9eb.rlib" "/tmp/grin-miner/target/release/deps/libocl_core-2a95d3f97d89c148.rlib" "/tmp/grin-miner/target/release/deps/libcl_sys-94ebc295dd731197.rlib" "/tmp/grin-miner/target/release/deps/libocl_core_vector-20b74dca604d2fdd.rlib" "/tmp/grin-miner/target/release/deps/libnum-9a5c13b129208bbf.rlib" "/tmp/grin-miner/target/release/deps/libnum_rational-3d803d44315e4ba4.rlib" "/tmp/grin-miner/target/release/deps/libnum_bigint-f7f551457291f84c.rlib" "/tmp/grin-miner/target/release/deps/librand-b6901789eca58733.rlib" "/tmp/grin-miner/target/release/deps/libnum_iter-b97da9cad15f276e.rlib" "/tmp/grin-miner/target/release/deps/libnum_integer-498e4bc9ae9b482c.rlib" "/tmp/grin-miner/target/release/deps/libnum_complex-9165645d39dafb71.rlib" "/tmp/grin-miner/target/release/deps/librustc_serialize-cc9f45dee15cc54b.rlib" "/tmp/grin-miner/target/release/deps/libenum_primitive-ba4a114519f8311e.rlib" "/tmp/grin-miner/target/release/deps/libnum_traits-37c5a88fd817209d.rlib" "/tmp/grin-miner/target/release/deps/libbitflags-3d1ea3d38b07332b.rlib" "/tmp/grin-miner/target/release/deps/libfailure-602c49260a465107.rlib" "/tmp/grin-miner/target/release/deps/libbacktrace-cec6e310a4a2ff1a.rlib" "/tmp/grin-miner/target/release/deps/libbacktrace_sys-cae5b2e09b822552.rlib" "/tmp/grin-miner/target/release/deps/libcfg_if-6ec81bd81205f848.rlib" "/tmp/grin-miner/target/release/deps/librustc_demangle-8c836fefbde76760.rlib" "/tmp/grin-miner/target/release/deps/libfutures-ac7eaa3c862a7fe5.rlib" "/tmp/grin-miner/target/release/deps/libnum_traits-a70d9e0dea0e1401.rlib" "/tmp/grin-miner/target/release/deps/libhashbrown-4827203f3434d129.rlib" "/tmp/grin-miner/target/release/deps/libscopeguard-2d0c2ae38ab83230.rlib" "/tmp/grin-miner/target/release/deps/libgrin_miner_plugin-7d0de6cc5d657c1d.rlib" "/tmp/grin-miner/target/release/deps/libserde_json-004053a5c8514388.rlib" "/tmp/grin-miner/target/release/deps/libryu-4189264dfe996109.rlib" "/tmp/grin-miner/target/release/deps/libitoa-d41983ca2ad8205f.rlib" "/tmp/grin-miner/target/release/deps/liblibc-165f62e367d49b96.rlib" "/tmp/grin-miner/target/release/deps/libbyteorder-0c6590e4fd79d26f.rlib" "/tmp/grin-miner/target/release/deps/libserde-8ec382251492118e.rlib" "/tmp/grin-miner/target/release/deps/libbyteorder-5bc0c701fbc6ad63.rlib" "/tmp/grin-miner/target/release/deps/libblake2_rfc-572229871a63232e.rlib" "/tmp/grin-miner/target/release/deps/libconstant_time_eq-b6a3c98a881caeb1.rlib" "/tmp/grin-miner/target/release/deps/libarrayvec-1b2abcea27cc3c20.rlib" "/tmp/grin-miner/target/release/deps/libnodrop-3a549cc447b987a8.rlib" "-Wl,--start-group" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-a6c2fb5f51e97d7d.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-9d32cc773d699b6c.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-3885d1f905b0299e.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-a019ad76690f9f23.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace-678bce0a071265cc.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-aaca73c29383aae2.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-69c714458d0ce6f9.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-bda2a901f2e1c906.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-2cf9ea15b1059ebc.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-04135f19ecb5a144.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-d702e69b69731c44.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-0b01dc43303caab5.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-3bc2f65a121a1ff9.rlib" "-Wl,--end-group" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-cf88e82531c452b2.rlib" "-Wl,-Bdynamic" "-lOpenCL" "-lOpenCL" "-lutil" "-lutil" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil" "-shared"
  = note: /usr/bin/ld: cannot find -lOpenCL
          /usr/bin/ld: cannot find -lOpenCL
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: could not compile `ocl_cuckatoo`.

To learn more, run the command again with --verbose.
cp: cannot stat 'target/release/libocl_cuckatoo.so': No such file or directory
warning: use of deprecated item 'libc::uint32_t': Use u32 instead.
  --> plugin/src/lib.rs:55:2
   |
55 |     uint32_t,             // header length
   |     ^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: use of deprecated item 'libc::uint64_t': Use u64 instead.
  --> plugin/src/lib.rs:56:2
   |
56 |     uint64_t,             // nonce
   |     ^^^^^^^^

warning: use of deprecated item 'libc::uint32_t': Use u32 instead.
  --> plugin/src/lib.rs:57:2
   |
57 |     uint32_t,             // range
   |     ^^^^^^^^

warning: use of deprecated item 'libc::uint32_t': Use u32 instead.
  --> plugin/src/lib.rs:60:6
   |
60 | ) -> uint32_t;
   |      ^^^^^^^^

warning: use of deprecated item 'libc::uint32_t': Use u32 instead.
  --> plugin/src/lib.rs:78:16
   |
78 |     pub nthreads: uint32_t,
   |                   ^^^^^^^^

warning: use of deprecated item 'libc::uint32_t': Use u32 instead.
  --> plugin/src/lib.rs:80:14
   |
80 |     pub ntrims: uint32_t,
   |                 ^^^^^^^^

warning: use of deprecated item 'libc::uint32_t': Use u32 instead.
   --> plugin/src/lib.rs:152:17
    |
152 |     pub device_id: uint32_t,
    |                    ^^^^^^^^

warning: use of deprecated item 'libc::uint32_t': Use u32 instead.
   --> plugin/src/lib.rs:154:17
    |
154 |     pub edge_bits: uint32_t,
    |                    ^^^^^^^^

warning: use of deprecated item 'libc::uint32_t': Use u32 instead.
   --> plugin/src/lib.rs:164:18
    |
164 |     pub iterations: uint32_t,
    |                     ^^^^^^^^

warning: use of deprecated item 'libc::uint64_t': Use u64 instead.
   --> plugin/src/lib.rs:166:23
    |
166 |     pub last_start_time: uint64_t,
    |                          ^^^^^^^^

warning: use of deprecated item 'libc::uint64_t': Use u64 instead.
   --> plugin/src/lib.rs:168:21
    |
168 |     pub last_end_time: uint64_t,
    |                        ^^^^^^^^

warning: use of deprecated item 'libc::uint64_t': Use u64 instead.
   --> plugin/src/lib.rs:170:26
    |
170 |     pub last_solution_time: uint64_t,
    |                             ^^^^^^^^

warning: use of deprecated item 'libc::uint64_t': Use u64 instead.
   --> plugin/src/lib.rs:233:10
    |
233 |     pub id: uint64_t,
    |             ^^^^^^^^

warning: use of deprecated item 'libc::uint64_t': Use u64 instead.
   --> plugin/src/lib.rs:235:13
    |
235 |     pub nonce: uint64_t,
    |                ^^^^^^^^

warning: use of deprecated item 'libc::uint64_t': Use u64 instead.
   --> plugin/src/lib.rs:237:14
    |
237 |     pub proof: [uint64_t; PROOFSIZE],
    |                 ^^^^^^^^

   Compiling ocl_cuckaroo v1.0.2 (/tmp/grin-miner/ocl_cuckaroo)
warning: use of deprecated item 'libc::uint32_t': Use u32 instead.
  --> ocl_cuckaroo/src/lib.rs:72:17
   |
72 |     header_length: uint32_t,
   |                    ^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: use of deprecated item 'libc::uint64_t': Use u64 instead.
  --> ocl_cuckaroo/src/lib.rs:73:9
   |
73 |     nonce: uint64_t,
   |            ^^^^^^^^

warning: use of deprecated item 'libc::uint32_t': Use u32 instead.
  --> ocl_cuckaroo/src/lib.rs:74:10
   |
74 |     _range: uint32_t,
   |             ^^^^^^^^

warning: use of deprecated item 'libc::uint32_t': Use u32 instead.
  --> ocl_cuckaroo/src/lib.rs:77:6
   |
77 | ) -> uint32_t {
   |      ^^^^^^^^

warning: method is never used: `nodes`
   --> ocl_cuckaroo/src/finder.rs:170:2
    |
170 |     fn nodes(&self) -> impl Iterator<Item = &u32> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "/tmp/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.0.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.1.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.10.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.11.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.12.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.13.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.14.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.15.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.2.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.3.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.4.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.5.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.6.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.7.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.8.rcgu.o" "/tmp/grin-miner/target/release/deps/ocl_cuckaroo.ocl_cuckaroo.f28w7ltk-cgu.9.rcgu.o" "-o" "/tmp/grin-miner/target/release/deps/libocl_cuckaroo.so" "-Wl,--version-script=/tmp/rustcQfSUU9/list" "/tmp/grin-miner/target/release/deps/ocl_cuckaroo.3a288qk8ou1nl0zg.rcgu.o" "-Wl,--gc-sections" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/tmp/grin-miner/target/release/deps" "-L" "/tmp/grin-miner/target/release/build/backtrace-sys-c06179d02ff280b6/out" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/grin-miner/target/release/deps/libocl-6ffa61d4f4954378.rlib" "/tmp/grin-miner/target/release/deps/libqutex-6dffd7181766d36a.rlib" "/tmp/grin-miner/target/release/deps/libcrossbeam-a33363128528f52e.rlib" "/tmp/grin-miner/target/release/deps/libcrossbeam_queue-6769d25ad3310111.rlib" "/tmp/grin-miner/target/release/deps/libcrossbeam_channel-1d882d4c1ef5456e.rlib" "/tmp/grin-miner/target/release/deps/libcrossbeam_deque-a6a5b9a03ea16c2a.rlib" "/tmp/grin-miner/target/release/deps/libcrossbeam_epoch-54c7b6b58321d000.rlib" "/tmp/grin-miner/target/release/deps/libscopeguard-aa02c8d466759377.rlib" "/tmp/grin-miner/target/release/deps/libmemoffset-fd63a4603bd61145.rlib" "/tmp/grin-miner/target/release/deps/libcrossbeam_utils-4cd75011f8777a01.rlib" "/tmp/grin-miner/target/release/deps/liblazy_static-0d6fc211b0b9e9eb.rlib" "/tmp/grin-miner/target/release/deps/libocl_core-2a95d3f97d89c148.rlib" "/tmp/grin-miner/target/release/deps/libcl_sys-94ebc295dd731197.rlib" "/tmp/grin-miner/target/release/deps/libocl_core_vector-20b74dca604d2fdd.rlib" "/tmp/grin-miner/target/release/deps/libnum-9a5c13b129208bbf.rlib" "/tmp/grin-miner/target/release/deps/libnum_rational-3d803d44315e4ba4.rlib" "/tmp/grin-miner/target/release/deps/libnum_bigint-f7f551457291f84c.rlib" "/tmp/grin-miner/target/release/deps/librand-b6901789eca58733.rlib" "/tmp/grin-miner/target/release/deps/libnum_iter-b97da9cad15f276e.rlib" "/tmp/grin-miner/target/release/deps/libnum_integer-498e4bc9ae9b482c.rlib" "/tmp/grin-miner/target/release/deps/libnum_complex-9165645d39dafb71.rlib" "/tmp/grin-miner/target/release/deps/librustc_serialize-cc9f45dee15cc54b.rlib" "/tmp/grin-miner/target/release/deps/libenum_primitive-ba4a114519f8311e.rlib" "/tmp/grin-miner/target/release/deps/libnum_traits-37c5a88fd817209d.rlib" "/tmp/grin-miner/target/release/deps/libbitflags-3d1ea3d38b07332b.rlib" "/tmp/grin-miner/target/release/deps/libfailure-602c49260a465107.rlib" "/tmp/grin-miner/target/release/deps/libbacktrace-cec6e310a4a2ff1a.rlib" "/tmp/grin-miner/target/release/deps/libbacktrace_sys-cae5b2e09b822552.rlib" "/tmp/grin-miner/target/release/deps/libcfg_if-6ec81bd81205f848.rlib" "/tmp/grin-miner/target/release/deps/librustc_demangle-8c836fefbde76760.rlib" "/tmp/grin-miner/target/release/deps/libfutures-ac7eaa3c862a7fe5.rlib" "/tmp/grin-miner/target/release/deps/libnum_traits-a70d9e0dea0e1401.rlib" "/tmp/grin-miner/target/release/deps/libhashbrown-4827203f3434d129.rlib" "/tmp/grin-miner/target/release/deps/libscopeguard-2d0c2ae38ab83230.rlib" "/tmp/grin-miner/target/release/deps/libgrin_miner_plugin-7d0de6cc5d657c1d.rlib" "/tmp/grin-miner/target/release/deps/libserde_json-004053a5c8514388.rlib" "/tmp/grin-miner/target/release/deps/libryu-4189264dfe996109.rlib" "/tmp/grin-miner/target/release/deps/libitoa-d41983ca2ad8205f.rlib" "/tmp/grin-miner/target/release/deps/liblibc-165f62e367d49b96.rlib" "/tmp/grin-miner/target/release/deps/libbyteorder-0c6590e4fd79d26f.rlib" "/tmp/grin-miner/target/release/deps/libserde-8ec382251492118e.rlib" "/tmp/grin-miner/target/release/deps/libbyteorder-5bc0c701fbc6ad63.rlib" "/tmp/grin-miner/target/release/deps/libblake2_rfc-572229871a63232e.rlib" "/tmp/grin-miner/target/release/deps/libconstant_time_eq-b6a3c98a881caeb1.rlib" "/tmp/grin-miner/target/release/deps/libarrayvec-1b2abcea27cc3c20.rlib" "/tmp/grin-miner/target/release/deps/libnodrop-3a549cc447b987a8.rlib" "-Wl,--start-group" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-a6c2fb5f51e97d7d.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-9d32cc773d699b6c.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-3885d1f905b0299e.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-a019ad76690f9f23.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace-678bce0a071265cc.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-aaca73c29383aae2.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-69c714458d0ce6f9.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-bda2a901f2e1c906.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-2cf9ea15b1059ebc.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-04135f19ecb5a144.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-d702e69b69731c44.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-0b01dc43303caab5.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-3bc2f65a121a1ff9.rlib" "-Wl,--end-group" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-cf88e82531c452b2.rlib" "-Wl,-Bdynamic" "-lOpenCL" "-lOpenCL" "-lutil" "-lutil" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil" "-shared"
  = note: /usr/bin/ld: cannot find -lOpenCL
          /usr/bin/ld: cannot find -lOpenCL
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: could not compile `ocl_cuckaroo`.

To learn more, run the command again with --verbose.
cp: cannot stat 'target/release/libocl_cuckaroo.so': No such file or directory
`

**Comment by quentinlesceller** [comment]
`usr/bin/ld: cannot find -lOpenCL`. Looks like OpenCL is missing?

**Comment by OlegWebmaster** [comment]
It was decided! It was necessary to add the following paths to the PATH variable:
`/opt/cuda/include:/opt/cuda/bin`
(Arch linux)
