### ISSUE TITLE
Cuckarooz29 implementation?

### ISSUE THREAD

**Issue by dagonharett** [mimblewimble/grin-miner#250]
Now that [HardFork3](https://github.com/mimblewimble/grin/pull/3334) is merged and [released](https://forum.grin.mw/t/grin-grin-wallet-4-0-0-released/7504), I wonder if @tromp or someone else could find the time to add an official implementation here.

Sorry to nag you about this, but in my view you should have released at least one working mining implementation of Cuckarooz29 alongside with `4.0.0`. It could be just a slow CPU implementation. The goal is to have something to test with.

**Comment by tromp** [comment]
There's a slow CPU miner in https://github.com/tromp/cuckoo/tree/master/src/cuckarooz
Run "make simple29" in that directory.
A CUDA miner will be made available right around hard fork time.

**Comment by maxmalysh** [comment]
So the fork is 7 hours away and there are no GPU miners supporting it? Just wow.

**Comment by tromp** [comment]
The fork is over a day away and CUDA support was just added to the PR.
