### ISSUE TITLE
Error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mrschaeffer2018** [mimblewimble/grin-miner#258]
When i try to run the miner says:
error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
I have cuda 9.0 i can't upgrade and ubuntu 16.04 how can i solve this issue?  thanks.

**Comment by quentinlesceller** [comment]
You need libssl-dev installed. That should fix the issue.

**Comment by mrschaeffer2018** [comment]
i have libssl-dev installed but i'm only able to get the 1.0 not the 1.1 version and i can't upgrade the hole system just to get a 1.1 version, there is no other way? I'm in cuda 9.0.

**Comment by quentinlesceller** [comment]
Did you compile the miner from sources?
