### ISSUE TITLE
support different SIMD types and multiple cuckoo sizes

### ISSUE THREAD

**Issue by tromp** [mimblewimble/grin-miner#34]
Before I suggested using
mean_miner
mean_sse2_miner
mean_avx2_miner

Perhaps these could be combined with some modest graph size choice, like
mean_30_miner
mean_31_miner
etcetera.
We don't need anything bigger than 31 for now. But we'll want ability to test a non-30 size.

**Comment by yeastplume** [comment]
think we're good here
