### ISSUE TITLE
Unclear whether attempts finish

### ISSUE THREAD

**Issue by yorickdowne** [mimblewimble/grin-miner#36]
With a slow miner (0.06 gps) and a stratum server set to attempt_time_per_block = 15, no accepted shares are recorded within a 25-hour period. It is unclear from the log whether the attempt ever finishes. @tromp states that "if a new job is just to incorporate new txs, then it shld NOT abort the current graph being worked on" and "i think the log wld be more helpful if it reports on the finished mining attempts, e.g. show number of cycles found"

I'm happy to run further tests to see whether there is a bug here. Right now I've set attempt time to 999, and that did generate an accepted share in under 15 minutes, as expected.

**Comment by yeastplume** [comment]
solvers no longer stop unless block height changes or a solution is found
