### ISSUE TITLE
"cargo build" return an error and installation fail

### ISSUE THREAD

**Issue by gammateta** [mimblewimble/grin-miner#38]
Compiling byteorder v1.2.6
   Compiling enumset v0.3.10
error[E0658]: 128-bit type is unstable (see issue #35118)
   --> /home/parallels/.cargo/registry/src/github.com-1ecc6299db9ec823/enumset-0.3.10/src/lib.rs:120:42
    |
120 |     fn repr_to_u128(bits: Self::Repr) -> u128;
    |                                          ^^^^

error[E0658]: 128-bit type is unstable (see issue #35118)
   --> /home/parallels/.cargo/registry/src/github.com-1ecc6299db9ec823/enumset-0.3.10/src/lib.rs:121:29
    |
121 |     fn repr_from_u128(bits: u128) -> Self::Repr;
    |                             ^^^^

error[E0658]: 128-bit type is unstable (see issue #35118)
   --> /home/parallels/.cargo/registry/src/github.com-1ecc6299db9ec823/enumset-0.3.10/src/lib.rs:174:30
    |
174 |     pub fn to_bits(&self) -> u128 {
    |                              ^^^^

error[E0658]: 128-bit type is unstable (see issue #35118)
   --> /home/parallels/.cargo/registry/src/github.com-1ecc6299db9ec823/enumset-0.3.10/src/lib.rs:182:28
    |
182 |     pub fn from_bits(bits: u128) -> Self {
    |                            ^^^^

error: aborting due to 4 previous errors

error: Could not compile `enumset`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by ivy** [comment]
@gammateta It sounds like you're using an outdated Rust. What version (`rustc --version`) are you using?

**Comment by gammateta** [comment]
rustc 1.25.0

**Comment by ivy** [comment]
I'm not 100% sure when exactly 128-bit types became stable but you shouldn't have this issue with the latest release (1.29.0). You can install it with [rustup](https://rustup.rs/).

**Comment by gtire** [comment]
I have disinstalled Rustc the reinstalled using your link but I still get rustc 1.25.0

**Comment by bokobza** [comment]
I used this to install it and it worked for me:
`curl -sSf https://static.rust-lang.org/rustup.sh | sh`

Saw that in https://github.com/rust-lang-nursery/rustup.rs/issues/953#issuecomment-416680741
