### ISSUE TITLE
GPUAssert: out of memory with more than 1 GPU activated

### ISSUE THREAD

**Issue by photis** [mimblewimble/grin-miner#45]
Running grin-miner with more than 1 GPU results in a 
`Device 0 GPUassert: out of memory /home/photis/.cargo/git/checkouts/cuckoo-miner-4752934f0f1f2bfe/7862dfe/src/cuckoo_sys/plugins/cuckoo/src/cuckatoo/mean.cu 391`. Error didn't occur before switch to v0.4.0.

Moreover, even though multiple GPUs are activated, only Device 0 shows any activity in `nvidia-smi`. Notice how it is also Device 0 that gives the `out of memory` error, while this device runs fine when it is the sole GPU activated. 

Error log at: https://gist.github.com/photis/0325b5d9b1703e469a288b4698dd3b9c#file-grin-miner-log-for-v0-4-0

Ubuntu Linux 18.04.1
CUDA 9.2.148-1
Nvidia drivers 396.44-1
Grin-Miner version 0.4.0 (git bffce19)

**Comment by yeastplume** [comment]
Can you try again with latest master? Should be corrected.

**Comment by photis** [comment]
Seems to hold (for now), running 2 GPUs simultaneously for 10 minutes without an issue. Would crash within a few seconds before, so it looks like you solved it. Well done! Will try to keep an eye on it for the rest of the day.

**Comment by photis** [comment]
It has held for over an hour now, I think we can assume this issue closed.
