### ISSUE TITLE
Cannot compile on Mac OS 10.14 Mojave with build-cuda-plugins

### ISSUE THREAD

**Issue by fafrd** [mimblewimble/grin-miner#47]
Hey, I'm unable to compile under Mojave when I have the feature build-cuda-plugins enabled. I get this error when running `cargo build --release`:
```
--- stderr
nvcc fatal   : The version ('10.0') of the host compiler ('Apple clang') is not supported
CMake Error at cuckatoo_cuda_29_generated_mean.cu.o.Release.cmake:219 (message):
  Error generating
  /Users/fafrd/Documents/crypto/grin/grin-miner/target/release/build/cuckoo_miner-1452aa9dd2467131/out/build/CMakeFiles/cuckatoo_cuda_29.dir/cuckoo/src/cuckatoo/./cuckatoo_cuda_29_generated_mean.cu.o
```

I tried using gcc5 instead, which I installed via macports; I then ran using gcc5 with
`CUDA_HOST_COMPILER=x86_64-apple-darwin18-gcc-5.5.0 cargo build --release` 
and got this error:
```
--- stderr
nvcc fatal   : GNU C/C++ compiler is no longer supported as a host compiler on Mac OS X.
CMake Error at cuckatoo_cuda_29_generated_mean.cu.o.Release.cmake:219 (message):
  Error generating
  /Users/fafrd/Documents/crypto/grin/grin-miner/target/release/build/cuckoo_miner-1452aa9dd2467131/out/build/CMakeFiles/cuckatoo_cuda_29.dir/cuckoo/src/cuckatoo/./cuckatoo_cuda_29_generated_mean.cu.o
```

I have CUDA 10.0.3 and rust 1.29.2 installed.

**Comment by kngako** [comment]
Hi @fafrd, I had a related nvcc which had C or CXX related issues. I solved most of them by upgrading from gcc-6 to gcc-7.  Give it a try and let me know if it solves your problem.

Had to do a lot of "update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 15"  to make sure all C and CXX compilers are set to gcc-7. Things like c++, cc, and the likes weren't what they were supposed to be for reasons I can't recall.

**Comment by masonforest** [comment]
Hey @fafrd, I had this same issue.

Cuda [only supports XCode 9.4](https://docs.nvidia.com/cuda/cuda-installation-guide-mac-os-x/index.html#system-requirements) on Mac OSX 😕

To Downgrade to XCode 9.4:

1. Download [Xcode_9.4.xip](https://download.developer.apple.com/Developer_Tools/Xcode_9.4/Xcode_9.4.xip) [here](https://developer.apple.com/download/more/) 
2. Extract it: `xip -x Xcode_9.4.xip`
3. Move `/Applications/Xcode.app` to `/Applications/Xcode.app 10`
4. Move `/Downloads/Xcode.app` to `/Applications/Xcode.app`
5. Run: `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`
6. Run: `cargo build`
