### ISSUE TITLE
Miner stops mining by itself and process doesn't terminate

### ISSUE THREAD

**Issue by RyanZim** [mimblewimble/grin-miner#49]
I am CPU mining with the settings provided in the `grin-miner.toml` file contained in this repo (no settings changed). Running Linux; Lubuntu 18.04.1 LTS [Linux 4.15.0-36-generic (x86_64)].

With the grin server running and the grin wallet listening (on the same computer), I start `grin-miner` from the terminal. The tui appears, and it begins mining; my CPU and memory usage increase (CPUs flat out, memory still has headroom and isn't touching swapspace). However, within about a minute of starting, the CPU usage falls to normal levels (memory remains elevated), and the logging output to `grin-miner.log` changes; `INFO Mining:` lines are no longer being written. Here is my [grin-miner.log](https://github.com/mimblewimble/grin-miner/files/2508492/grin-miner.log)

At this point, if I terminate the miner by pressing `Q` in the tui window, the tui shuts down, and I'm returned to the terminal, but the process doesn't exit; my prompt never appears. Memory remains elevated. After pressing `Ctrl + C`, the process exits, my prompt appears, and memory usage returns to normal.

I have no clue what could be causing this, and unfortunately I don't know Rust to investigate further :frowning_face:

**Comment by xjtufjj** [comment]
Also encounter this issue. further more, I did the following thing: \

1. change the miner thread number to 12(my CPU is i7-8700k), the possiblity to encouter this issue it bigger. 

2. with the release build, the possibility is bigger. 

3. change the thread number to 1, not encouter this issue in 2 hours. 

The following is the log: 

Oct 24 15:00:07.096 INFO Mining: Cuck(at)oo at 0.6318121640026071 gps (graphs per second)
Oct 24 15:00:10.070 INFO Mining: Cuck(at)oo at 0.3280962262634204 gps (graphs per second)
Oct 24 15:00:13.043 INFO Mining: Cuck(at)oo at 0.3182468108059047 gps (graphs per second)
Oct 24 15:00:16.016 INFO Mining: Cuck(at)oo at 0.3201570874056792 gps (graphs per second)
Oct 24 15:00:18.025 INFO Status for worker 16 - Height: 8687, Difficulty: 1, (16/0/0)
Oct 24 15:00:19.100 INFO Mining: Cuck(at)oo at 0.32347888309779277 gps (graphs per second)
Oct 24 15:00:22.028 INFO Got a new job: JobTemplate { height: 8687, job_id: 6, difficulty: 1, pre_pow: "000100000000000021ef000000005bd018840101235e5e82430e8ecd756b9b9211ae8d98f4b93fb52b6c5e6411a712a680a76042d552c327f44cfe6c7d005d683f39cccf17eb2d3dd7be430b2985632c29d2841fd7fe4dc9425ed07915a94e9b5000f61159463a2911f92e1f17f59cc06563d6cf082193eca7e28d9ddc9ebcc4091698afa109f565132af6ea8df425cd774682b5b9414ba2476b4b84d12e7b06fc177e95422d2a3ebb090250298bfc371a1dce4c82353b2ea7e2c1f9f94ab8509d292cf6ef3aa48d4c818c012de6c5b5193c00000000000058330000000000004e8e0000000011dad45200000045" }
Oct 24 15:00:22.879 INFO Mining: Cuck(at)oo at 1.2161965777641521 gps (graphs per second)
Oct 24 15:00:25.082 INFO Mining: Cuck(at)oo at 1.2161965777641521 gps (graphs per second)
Oct 24 15:00:28.056 INFO Mining: Cuck(at)oo at 0.3238880965693555 gps (graphs per second)
Oct 24 15:00:31.029 INFO Mining: Cuck(at)oo at 0.334049012743447 gps (graphs per second)
Oct 24 15:00:34.003 INFO Mining: Cuck(at)oo at 0.33236822176831937 gps (graphs per second)

Oct 24 15:00:36.037 INFO Got a new job: JobTemplate { height: 8687, job_id: 7, difficulty: 1, pre_pow: "000100000000000021ef000000005bd018930101235e5e82430e8ecd756b9b9211ae8d98f4b93fb52b6c5e6411a712a680a76042d552c327f44cfe6c7d005d683f39cccf17eb2d3dd7be430b2985632c29d2841fd7fe4dc9425ed07915a94e9b5000f61159463a2911f92e1f17f59cc06563d6cf082193eca7e28d9ddc9ebcc4091698afa109f565132af6ea8df425cd7746d70600551290f0348c10b4cde6b519d18b53e85ba798986bd00da59dcf5f4795ce4c82353b2ea7e2c1f9f94ab8509d292cf6ef3aa48d4c818c012de6c5b5193c00000000000058330000000000004e8e0000000011dad45200000045" }
Oct 24 15:00:50.051 INFO Status for worker 16 - Height: 8687, Difficulty: 1, (16/0/0)
Oct 24 15:00:52.053 INFO Got a new job: JobTemplate { height: 8687, job_id: 8, difficulty: 1, pre_pow: "000100000000000021ef000000005bd018a20101235e5e82430e8ecd756b9b9211ae8d98f4b93fb52b6c5e6411a712a680a76042d552c327f44cfe6c7d005d683f39cccf17eb2d3dd7be430b2985632c29d2841fd7fe4dc9425ed07915a94e9b5000f61159463a2911f92e1f17f59cc06563d6cf082193eca7e28d9ddc9ebcc4091698afa109f565132af6ea8df425cd7746bc946c830445a72a4e9b89d1afb7983d26ad3201f37714da0565c6442d87ca0ace4c82353b2ea7e2c1f9f94ab8509d292cf6ef3aa48d4c818c012de6c5b5193c00000000000058330000000000004e8e0000000011dad45200000045" }
Oct 24 15:01:06.066 INFO Got a new job: JobTemplate { height: 8687, job_id: 9, difficulty: 1, pre_pow: "000100000000000021ef000000005bd018b10101235e5e82430e8ecd756b9b9211ae8d98f4b93fb52b6c5e6411a712a680a76042d552c327f44cfe6c7d005d683f39cccf17eb2d3dd7be430b2985632c29d2841fd7fe4dc9425ed07915a94e9b5000f61159463a2911f92e1f17f59cc06563d6cf082193eca7e28d9ddc9ebcc4091698afa109f565132af6ea8df425cd774616205a12b514a0f72465b03621126f764e00c358a04f3f8d034bf2a7e1f28187ce4c82353b2ea7e2c1f9f94ab8509d292cf6ef3aa48d4c818c012de6c5b5193c00000000000058330000000000004e8e0000000011dad45200000045" }

**Comment by PositronicBrain** [comment]
Same.

**Comment by ignopeverell** [comment]
It's a common issue at the moment and is being worked on. We should have an update on the miner in the next few days that solves this.

**Comment by xjtufjj** [comment]
with the latest code, the bug disappeared!

**Comment by RyanZim** [comment]
Confirmed fixed with the new code.
