### ISSUE TITLE
HTTP/1.1 400 Bad Request from the server

### ISSUE THREAD

**Issue by JYMiaw** [mimblewimble/grin-miner#50]
I built the grin server and grin-miner without any changes and tried to run as is, but I got this error on the miner side after successful connection:

Oct 24 15:33:11.982 DEBG sending request: {"id":"0","jsonrpc":"2.0","method":"getjobtemplate","params":null}
Oct 24 15:33:12.082 DEBG Received message: HTTP/1.1 400 Bad Request

The server would not honor the request from the miner and closed the connection after that. Would appreciate any insight or advice. Thanks!

**Comment by xjtufjj** [comment]
it's better to paste your configuration. I also build the miner and the grin from fresh state, everything is OK.

**Comment by JYMiaw** [comment]
Okay, here is the effective and relevant part(without logging configuration) of grin-miner.toml and grin-server.toml. Thanks a lot for helping look into it.

#########################################
### MINING CLIENT CONFIGURATION       ###
#########################################

[mining]

# whether to run the tui
run_tui = true

# listening grin stratum server url
stratum_server_addr = "127.0.0.1:13414"

[[mining.miner_plugin_config]]
edge_bits = 29
type_filter = "cuckatoo_mean_compat_cpu"
[mining.miner_plugin_config.device_parameters.0]
NUM_THREADS = 4

=============================================================
And then the grin-server.toml:

#########################################
### SERVER CONFIGURATION              ###
#########################################

#Server connection details
[server]

#the directory, relative to current, in which the grin blockchain
#is stored
db_root = "/home/user/dev/grin/target/debug/chain_data"

#the address on which services will listen, e.g. Transaction Pool
api_http_addr = "127.0.0.1:13413"

#path of the secret token used by the API to authenticate the calls
#comment it to disable basic auth
api_secret_path = "/home/user/dev/grin/target/debug/.api_secret"

chain_type = "Testnet4"

#the chain validation mode, defines how often (if at all) we
#want to run a full chain validation. Can be:
#"EveryBlock" - run full chain validation when processing each block (except during sync)
#"Disabled" - disable full chain validation (just run regular block validation)
chain_validation_mode = "Disabled"

#run the node in "full archive" mode (default is fast-sync, pruned node)
archive_mode = false

#skip waiting for sync on startup, (optional param, mostly for testing)
skip_sync_wait = false

#whether to run the ncurses TUI. Ncurses must be installed and this
#will also disable logging to stdout
run_tui = true

run_test_miner = false

#########################################
### SERVER P2P CONFIGURATION          ###
#########################################
#The P2P server details (i.e. the server that communicates with other
[server.p2p_config]

#The interface on which to listen.
#0.0.0.0 will listen on all interfaces, allowing others to interact
#127.0.0.1 will listen on the local machine only
host = "0.0.0.0"

#The port on which to listen.
port = 13414

#how to seed this server, can be None, List or DNSSeed
seeding_type = "DNSSeed"

# 7 = Bit flags for FULL_NODE
#This structure needs to be changed internally, to make it more configurable
[server.p2p_config.capabilities]
bits = 7


#########################################
### MEMPOOL CONFIGURATION             ###
#########################################
[server.pool_config]

#base fee that's accepted into the pool
accept_fee_base = 1000000

#maximum number of transactions allowed in the pool
max_pool_size = 50000


#########################################
### DANDELION CONFIGURATION           ###
#########################################
[server.dandelion_config]

#dandelion relay time (choose new relay peer every n secs)
relay_secs = 600

#fluff and broadcast after embargo expires if tx not seen on network
embargo_secs = 180

#run dandelion stem/fluff processing every n secs (stem tx aggregation in this window)
patience_secs = 10

#dandelion stem probability (stem 90% of the time, fluff 10% of the time)
stem_probability = 90

################################################
### STRATUM MINING SERVER CONFIGURATION      ###
################################################
[server.stratum_mining_config]

#whether stratum server is enabled
enable_stratum_server = false

#what port and address for the stratum server to listen on
stratum_server_addr = "127.0.0.1:13416"

#the amount of time, in seconds, to attempt to mine on a particular
#header before stopping and re-collecting transactions from the pool
attempt_time_per_block = 15

#the minimum acceptable share difficulty to request from miners
minimum_share_difficulty = 1

#the wallet receiver to which coinbase rewards will be sent
wallet_listener_url = "http://127.0.0.1:13415"

#whether to ignore the reward (mostly for testing)
burn_reward = false

**Comment by JYMiaw** [comment]
I have to change the server config to allow stratum - issue resolved and closed
