### ISSUE TITLE
CUDA Related GPUAssert with Cuckatoo 29 mean cuda solver

### ISSUE THREAD

**Issue by gonta71** [mimblewimble/grin-miner#51]
I ran into the following crash when running grin-miner with cuckatoo 29:

https://gist.github.com/gonta71/f6712b23d20aecaa9f9445a7c7b5da06

This is on Xenial with the following drivers:

$ modinfo nvidia
filename:       /lib/modules/4.15.0-36-generic/updates/dkms/nvidia.ko
alias:          char-major-195-*
version:        410.66
supported:      external
license:        NVIDIA
srcversion:     E6823ED882C76894D74F1C2
alias:          pci:v000010DEd00000E00sv*sd*bc04sc80i00*
alias:          pci:v000010DEd*sv*sd*bc03sc02i00*
alias:          pci:v000010DEd*sv*sd*bc03sc00i00*
depends:        ipmi_msghandler
retpoline:      Y
name:           nvidia

and CUDA with the latest version 10.0.130_410.48_linux.

Anything else that is useful to report?

**Comment by yeastplume** [comment]
rewritten since
