### ISSUE TITLE
Mining Status: Starting miner and awaiting first graph time

### ISSUE THREAD

**Issue by xiaogazhang** [mimblewimble/grin-miner#56]
My grin miner always says "Mining Status: Starting miner and awaiting first graph time...", and not works. The miner can get job from server, but not submit any share. What's the reason? Thanks!

Grin server:
Cuckoo Size: 30
This is Grin version 0.4.1 (git 0.4.0-133-gaf595fa), built for x86_64-unknown-linux-gnu by rustc 1.30.1 (1433507eb 2018-11-07). Built with profile "release", features "".  

Grin miner:
Plugin: cuckatoo_mean_compat_cpu_29
This is Grin-Miner version 0.4.0 (git 648e49e), built for x86_64-unknown-linux-gnu by rustc 1.30.1 (1433507eb 2018-11-07).  Built with profile "release", features "" on Sun, 25 Nov 2018 13:54:57 GMT.

System:
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

Hardware:
2 CPU , 8G Memory

**Comment by xiaogazhang** [comment]
I switch to an other machine, the miner works.

The new one is:
Ubuntu 14.04 x64
8 CPU, 16G Memory

**Comment by illera88** [comment]
That's probably because you are not running the wallet

**Comment by asocjal** [comment]
I ad the same for poor CPU, when average time to find cycle is higher than attempt_time_per_block. It looks, this issue is the same:

https://github.com/mimblewimble/grin-miner/issues/67

**Comment by yeastplume** [comment]
should be fixed now

**Comment by canselcik** [comment]
FWIW I am having the same issue with a 1070 on both `cuckatoo` and `cockaroo` if GPU is involved at all. `nvidia-smi` shows no memory is used. 

What was the fix? I built from `master` just today.

**Comment by invis87** [comment]
Any answers?
I am trying to mine on Ubuntu 16.04 with 8 CPU + GeForce GTX 1050 Ti and have `Option::unwrap()` on a `None` value': src/libcore/option.rs` :(
How to fix that?
Tried to use release and build from sources - nothing helps.
