### ISSUE TITLE
ERRO Failed to submit a solution

### ISSUE THREAD

**Issue by Goffmann** [mimblewimble/grin-miner#65]
Dec 11 23:37:39.074 ERRO Failed to submit a solution: Object({"code": Number(-32502), "message": String("Failed to validate solution")})

when i run grin-miner, i got this error, and i don't know how to fix it , help me !!!

and i have other question:
1. how to run the grin wallet listen in backgrounder?
2. run the grin-miner backgrounder?

**Comment by yeastplume** [comment]
shouldn't happen anymore using default plugin configuration
