### ISSUE TITLE
Grin-Miner Segmentation Fault: 11

### ISSUE THREAD

**Issue by philsalesses** [mimblewimble/grin-miner#68]
After running grin-miner for a short period of time >5 minutes < 1 hr it crashes. Several times and displays:

Segmentation Fault: 11

Ideas? 

Screenshot of grin-miner is on the bottom left.

![image](https://user-images.githubusercontent.com/757781/50049773-c23ca600-00a1-11e9-9adb-c4edbce4c8b6.png)

**Comment by yeastplume** [comment]
Solvers have been updated quite a lot since, please re-open if you see this again
