### ISSUE TITLE
grin-miner crash on Tesla K80

### ISSUE THREAD

**Issue by beniamino38** [mimblewimble/grin-miner#71]
```Dec 21 12:53:29.169 INFO This is Grin-Miner version 0.4.2 (git c3dc949), built for x86_64-unknown-linux-gnu by rustc 1.31.1 (b6c32da9b 2018-12-18).
Dec 21 12:53:29.169 DEBG Built with profile "debug", features "" on Fri, 21 Dec 2018 12:48:58 GMT.
Dec 21 12:53:29.170 DEBG Starting solvers
Dec 21 12:53:29.170 DEBG Loading miner plugin: /ebs-volume/grin-miner/target/debug/plugins/cuckaroo_mean_cuda_29.cuckooplugin
Dec 21 12:53:29.171 DEBG Loading miner plugin: /ebs-volume/grin-miner/target/debug/plugins/cuckaroo_mean_cuda_29.cuckooplugin
Dec 21 12:53:29.346 ERRO 
thread 'unnamed' panicked at 'called `Option::unwrap()` on a `None` value': libcore/option.rs:355stack backtrace:
   0:     0x55b1742930a6 - backtrace::backtrace::libunwind::trace::h67350768f045b497
                        at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::hfa024cb19a0de9eb
                        at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/mod.rs:42
   1:     0x55b17428d7b3 - backtrace::capture::Backtrace::new_unresolved::ha4147d1e7635c793
                        at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:88
   2:     0x55b17428d70d - backtrace::capture::Backtrace::new::ha063bbb620b340dc
                        at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:63
   3:     0x55b1741c04d7 - grin_miner_util::logger::send_panic_to_log::{{closure}}::hfac4cc7196891fa5
                        at util/src/logger.rs:120
   4:     0x55b1742fde16 - std::panicking::rust_panic_with_hook::hde420d6fd4455550
                        at libstd/panicking.rs:480
   5:     0x55b1742fd961 - std::panicking::continue_panic_fmt::h8f394f3c578bcc76
                        at libstd/panicking.rs:390
   6:     0x55b1742fd845 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:     0x55b17434451c - core::panicking::panic_fmt::hca5dc4e8b320bc56
                        at libcore/panicking.rs:77
   8:     0x55b17434444b - core::panicking::panic::hca17aeb7dac42859
                        at libcore/panicking.rs:52
   9:     0x55b17415d77f - <core::option::Option<T>>::unwrap::hc8df5814702a6f72
                        at libcore/macros.rs:20
  10:     0x55b1741610ee - cuckoo_miner::miner::miner::CuckooMiner::solver_thread::h848c18772f611022
                        at cuckoo-miner/src/miner/miner.rs:94
  11:     0x55b17418fb48 - cuckoo_miner::miner::miner::CuckooMiner::start_solvers::{{closure}}::h729931352bc84513
                        at cuckoo-miner/src/miner/miner.rs:197
  12:     0x55b174186626 - std::sys_common::backtrace::__rust_begin_short_backtrace::h397d2345fc25ddab
                        at libstd/sys_common/backtrace.rs:136
  13:     0x55b17416e8f5 - std::thread::Builder::spawn::{{closure}}::{{closure}}::h54f1a8c116640dc6
                        at libstd/thread/mod.rs:409
  14:     0x55b17418a705 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hec8b12a95861bc7b
                        at libstd/panic.rs:313
  15:     0x55b1741900b1 - std::panicking::try::do_call::ha82787b69d535607
                        at libstd/panicking.rs:310
  16:     0x55b17430dea9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  17:     0x55b17418fde7 - std::panicking::try::h404ccb56d5a47fba
                        at libstd/panicking.rs:289
  18:     0x55b17418a747 - std::panic::catch_unwind::h261c065e7fe14204
                        at libstd/panic.rs:392
  19:     0x55b17416e6cc - std::thread::Builder::spawn::{{closure}}::h9615fcb6e6a68e9c
                        at libstd/thread/mod.rs:408
  20:     0x55b17416e988 - <F as alloc::boxed::FnBox<A>>::call_box::h189d983fe07e5b3b
                        at liballoc/boxed.rs:672
  21:     0x55b1742fb26d - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h9d902c911a417e39
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h44127e03e78ca137
                        at libstd/sys_common/thread.rs:24
  22:     0x55b1742ec5c5 - std::sys::unix::thread::Thread::new::thread_start::h8f17b97f2223146c
                        at libstd/sys/unix/thread.rs:90
  23:     0x7ff2e62a36da - start_thread
  24:     0x7ff2e5db488e - __clone
  25:                0x0 - <unknown>```

**Comment by yeastplume** [comment]
I'm not able to test this, perhaps someone else can confirm?

**Comment by pirocks** [comment]
I have gotten a similar stacktrace on a gtx 1070 system, without trying to do any gpu mining.

**Comment by sowhynot** [comment]
getting the same error with a Tesla M60.
Config 
[[mining.miner_plugin_config]]
plugin_name = "cuckaroo_cuda_29"
[mining.miner_plugin_config.parameters]
device = 1

Jan 09 15:21:51.570 INFO This is Grin-Miner version 0.5.1 (git 0.5.1), built for x86_64-unknown-linux-gnu by rustc 1.31.1 (b6c32da9b 2018-12-18).
Jan 09 15:21:51.570 DEBG Built with profile "release", features "CURSIVE, DEFAULT, OCL_CUCKATOO, OPENCL, TUI" on Mon, 07 Jan 2019 22:53:05 GMT.
Jan 09 15:21:51.570 DEBG Starting solvers
Jan 09 15:21:51.570 DEBG Loading miner plugin: /home/myuser/grin_release/grin-miner-0.5.1/plugins/cuckaroo_cuda_29.cuckooplugin
Jan 09 15:21:51.570 DEBG Loading miner plugin: /home/myuser/grin_release/grin-miner-0.5.1/plugins/cuckaroo_cuda_29.cuckooplugin
Jan 09 15:21:51.665 ERRO
thread 'unnamed' panicked at 'called `Option::unwrap()` on a `None` value': libcore/option.rs:355stack backtrace:
   0:     0x55d81841623d - backtrace::backtrace::trace::h6a895d5d279a8d2f
   1:     0x55d818415452 - <backtrace::capture::Backtrace as core::default::Default>::default::h03a8d770395d927e
   2:     0x55d8184154c9 - backtrace::capture::Backtrace::new::h2eb1c11c92f206be
   3:     0x55d8183ea030 - grin_miner_util::logger::send_panic_to_log::{{closure}}::h7d93e5b54f679b13
   4:     0x55d818440896 - std::panicking::rust_panic_with_hook::hde420d6fd4455550
                        at libstd/panicking.rs:480
   5:     0x55d8184403e1 - std::panicking::continue_panic_fmt::h8f394f3c578bcc76
                        at libstd/panicking.rs:390
   6:     0x55d8184402c5 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:     0x55d818486f8c - core::panicking::panic_fmt::hca5dc4e8b320bc56
                        at libcore/panicking.rs:77
   8:     0x55d818486ebb - core::panicking::panic::hca17aeb7dac42859
                        at libcore/panicking.rs:52
   9:     0x55d8183cef18 - cuckoo_miner::miner::miner::CuckooMiner::solver_thread::h535da4c06c3d9c30
  10:     0x55d8183d14b3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0d585e4948650748
  11:     0x55d8183d34b6 - std::panicking::try::do_call::ha175e9372e95fa8f
  12:     0x55d818450929 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  13:     0x55d8183dacdd - <F as alloc::boxed::FnBox<A>>::call_box::h09654cb679790681
  14:     0x55d81843dced - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h9d902c911a417e39
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h44127e03e78ca137
                        at libstd/sys_common/thread.rs:24
  15:     0x55d81842f045 - std::sys::unix::thread::Thread::new::thread_start::h8f17b97f2223146c
                        at libstd/sys/unix/thread.rs:90
  16:     0x7f98ca7816b9 - start_thread
  17:     0x7f98ca2a141c - clone
  18:                0x0 - <unknown>

**Comment by beniamino38** [comment]
This was definitely due to misconfigured nvidia drivers in my case, so I'm closing it.

**Comment by emkman** [comment]
Same issue on gtx 1070. OpenCL works fine so something CUDA configuration related? I have tried with releases and building from source.
