### ISSUE TITLE
Cuckatoo31 doesn't work on Nvidia Tesla P100 et V100 GPUs

### ISSUE THREAD

**Issue by mably** [mimblewimble/grin-miner#72]
Here are the logs we get when running the cuda31 utility software with `-E 2 -r 100` parameters:

Tesla P100: https://pastebin.com/M3Gnpi7t
Tesla V100: https://pastebin.com/HLUngKbQ

**Comment by yeastplume** [comment]
are they working now after the most recent updates?

**Comment by mably** [comment]
Yep, our latest tests were successul.
