### ISSUE TITLE
Cuckaroo29 doesn't seem to work with a RTX 2070 gpu

### ISSUE THREAD

**Issue by mably** [mimblewimble/grin-miner#76]
Here is what we get in the logs:

```
Dec 28 21:41:00.008 DEBG Mining: Plugin 0 - Device 1 (GeForce RTX 2070) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.000124314s; Graphs per second: 8044.146 - Total Attempts: 1935
```

**Comment by mably** [comment]
Looks like our RTX 2070 card might be faulty.

It would be great if anyone could confirm that cuckaroo29 works fine on their 2070 gpu.

**Comment by lehnberg** [comment]
I personally can't confirm @mably but looking at the [gpu mining stats page](https://github.com/mimblewimble/docs/wiki/GPU-Mining-Stats) it appears it has been working for others in the past at least.

**Comment by mably** [comment]
Yep it has even been working on our own RTX 2070 mid-december.
We just want to be sure it's not a recently introduced regression but just our card that has been damaged.

**Comment by yeastplume** [comment]
confirmed faulty card, I believe?
