### ISSUE TITLE
Plugins not built in Ubuntu on Windows 10

### ISSUE THREAD

**Issue by bergr01** [mimblewimble/grin-miner#78]
Enabled Linux subsystem on Windows 10 laptop, installed Ubuntu app, launched it, used sudo apt install to install all the prerequisites (or so I thought).

Cloned grin-miner repo, ran cargo build --release
After the build is finished (no error messages seen) can't seem to find a ./target/release/plugin folder or its contents

Mystified

**Comment by bergr01** [comment]
Looks like this was due to check for Windows in build.rs - it was logging some message via println! and doing a return, so the custom build command to build all the plugins was never executed. I commented out that Windows check and now the plugins are being built, just need to test whether they're actually working / able to produce an accepted share...

**Comment by yeastplume** [comment]
okay, glad you found it. I think we can remove that windows check, it's left over from a very long time ago and we're assuming grin-miner is linux only for the time being

**Comment by GandalfThePink** [comment]
Hi, can you explain in a little more detail what you did to fix that problem. I am having the same trouble on my Windows 10 machine.

**Comment by bergr01** [comment]
In cuckoo-miner/src/build.rs remove or comment out the following check:

if let Some(_) = windows_sysinfo {
                // Windows plugins not supported for now.. bye!
                return;
        }

On 1/5/19, GandalfThePink <notifications@github.com> wrote:
> Hi, can you explain in a little more detail what you did to fix that
> problem. I am having the same trouble on my Windows 10 machine.
>
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mimblewimble/grin-miner/issues/78#issuecomment-451638643


-- 
If I ever went to war, instead of throwing a grenade, I'd throw one of
those small pumpkins. Then maybe my enemy would pick up the pumpkin
and think about the futility of war. And that would give me the time I
need to hit him with a real grenade.

**Comment by GandalfThePink** [comment]
thanks for the quick answer. I was looking at the wrong build.rs ...

It seems to be working now

**Comment by yeastplume** [comment]
I've removed that windows check, was left over from a very long time ago and not needed now
